/// JMA EEW Forecast Region definitions.
///
/// See IS-QZSS-DCR-015 Table 4.1.2-12.
enum JmaEewForecastRegion {
  hokkaidoDoo(1, '北海道道央'),
  hokkaidoDoonan(2, '北海道道南'),
  hokkaidoDoohoku(3, '北海道道北'),
  hokkaidoDootoo(4, '北海道道東'),
  aomori(5, '青森'),
  iwate(6, '岩手'),
  miyagi(7, '宮城'),
  akita(8, '秋田'),
  yamagata(9, '山形'),
  fukushima(10, '福島'),
  ibaraki(11, '茨城'),
  tochigi(12, '栃木'),
  gunma(13, '群馬'),
  saitama(14, '埼玉'),
  chiba(15, '千葉'),
  tokyo(16, '東京'),
  izuOshima(17, '伊豆諸島'),
  ogasawara(18, '小笠原'),
  kanagawa(19, '神奈川'),
  niigata(20, '新潟'),
  toyama(21, '富山'),
  ishikawa(22, '石川'),
  fukui(23, '福井'),
  yamanashi(24, '山梨'),
  nagano(25, '長野'),
  gifu(26, '岐阜'),
  shizuoka(27, '静岡'),
  aichi(28, '愛知'),
  mie(29, '三重'),
  shiga(30, '滋賀'),
  kyoto(31, '京都'),
  osaka(32, '大阪'),
  hyogo(33, '兵庫'),
  nara(34, '奈良'),
  wakayama(35, '和歌山'),
  tottori(36, '鳥取'),
  shimane(37, '島根'),
  okayama(38, '岡山'),
  hiroshima(39, '広島'),
  yamaguchi(40, '山口'),
  tokushima(41, '徳島'),
  kagawa(42, '香川'),
  ehime(43, '愛媛'),
  kochi(44, '高知'),
  fukuoka(45, '福岡'),
  saga(46, '佐賀'),
  nagasaki(47, '長崎'),
  kumamoto(48, '熊本'),
  oita(49, '大分'),
  miyazaki(50, '宮崎'),
  kagoshima(51, '鹿児島'),
  amami(52, '奄美(群島)'),
  okinawaHonto(53, '沖縄本島'),
  daitojima(54, '大東島'),
  miyakojima(55, '宮古島'),
  yaeyama(56, '八重山'),
  hokkaidoRegion(57, '北海道'),
  tohokuRegion(58, '東北'),
  kantoRegion(59, '関東'),
  izuOshimaRegion(60, '伊豆諸島'),
  ogasawaraRegion(61, '小笠原'),
  hokurikuRegion(62, '北陸'),
  koshinRegion(63, '甲信'),
  tokaiRegion(64, '東海'),
  kinkiRegion(65, '近畿'),
  chugokuRegion(66, '中国'),
  shikokuRegion(67, '四国'),
  kyushuRegion(68, '九州'),
  amamiRegion(69, '奄美(群島)'),
  okinawaRegion(70, '沖縄'),
  other(80, 'その他の府県予報区および地方予報区')
  ;

  const JmaEewForecastRegion(this.code, this.name);

  final int code;
  final String name;

  static JmaEewForecastRegion fromCode(int code) =>
      values.firstWhere((e) => e.code == code);
}
