/// JMA Tsunami Forecast Region definitions.
///
/// See IS-QZSS-DCR-015 Table 4.1.2-18.
enum JmaTsunamiForecastRegion {
  hokkaidoPacificEast(100, '北海道太平洋沿岸東部'),
  hokkaidoPacificMiddle(101, '北海道太平洋沿岸中部'),
  hokkaidoPacificWest(102, '北海道太平洋沿岸西部'),
  hokkaidoSeaOfJapanNorth(110, '北海道日本海沿岸北部'),
  hokkaidoSeaOfJapanSouth(111, '北海道日本海沿岸南部'),
  okhotskSea(120, 'オホーツク海沿岸'),
  hokkaidoPacific(191, '北海道太平洋沿岸'),
  hokkaidoSeaOfJapan(192, '北海道日本海沿岸'),
  aomoriSeaOfJapan(200, '青森県日本海沿岸'),
  aomoriPacific(201, '青森県太平洋沿岸'),
  mutsuBay(202, '陸奥湾'),
  iwate(210, '岩手県'),
  miyagi(220, '宮城県'),
  akita(230, '秋田県'),
  yamagata(240, '山形県'),
  fukushima(250, '福島県'),
  aomori(281, '青森県'),
  tohokuPacific(291, '東北地方太平洋沿岸'),
  tohokuSeaOfJapan(292, '東北地方日本海沿岸'),
  ibaraki(300, '茨城県'),
  chibaKujukuriSotobo(310, '千葉県九十九里・外房'),
  chibaUchibobu(311, '千葉県内房'),
  tokyoBayInner(312, '東京湾内湾'),
  izuIslands(320, '伊豆諸島'),
  ogasawaraIslands(321, '小笠原諸島'),
  sagamiBayMiura(330, '相模湾・三浦半島'),
  niigataJoChuGe(340, '新潟県上中下越'),
  sado(341, '佐渡'),
  toyama(350, '富山県'),
  ishikawaNoto(360, '石川県能登'),
  ishikawaKaga(361, '石川県加賀'),
  fukui(370, '福井県'),
  shizuoka(380, '静岡県'),
  aichiOuter(390, '愛知県外海'),
  iseMikawaBay(391, '伊勢・三河湾'),
  mieSouth(400, '三重県南部'),
  chiba(481, '千葉県'),
  kanagawa(482, '神奈川県'),
  niigata(483, '新潟県'),
  ishikawa(484, '石川県'),
  aichi(485, '愛知県'),
  mie(486, '三重県'),
  kantoRegion(491, '関東地方'),
  izuOgasawaraIslands(492, '伊豆・小笠原諸島'),
  hokurikuRegion(493, '北陸地方'),
  tokaiRegion(494, '東海地方'),
  kyoto(500, '京都府'),
  osaka(510, '大阪府'),
  hyogoNorth(520, '兵庫県北部'),
  hyogoSetoInlandSea(521, '兵庫県瀬戸内海沿岸'),
  awajiIslandSouth(522, '淡路島南部'),
  wakayama(530, '和歌山県'),
  tottori(540, '鳥取県'),
  shimaneIzumoIwami(550, '島根県出雲・石見'),
  oki(551, '隠岐'),
  okayama(560, '岡山県'),
  hiroshima(570, '広島県'),
  tokushima(580, '徳島県'),
  kagawa(590, '香川県'),
  ehimeUwakai(600, '愛媛県宇和海沿岸'),
  ehimeSetoInlandSea(601, '愛媛県瀬戸内海沿岸'),
  kochi(610, '高知県'),
  hyogo(681, '兵庫県'),
  shimane(682, '島根県'),
  ehime(683, '愛媛県'),
  kinkiShikokuPacific(691, '近畿四国太平洋沿岸'),
  kinkiChugokuSeaOfJapan(692, '近畿中国日本海沿岸'),
  setoInlandSeaCoast(693, '瀬戸内海沿岸'),
  yamaguchiSeaOfJapan(700, '山口県日本海沿岸'),
  yamaguchiSetoInlandSea(701, '山口県瀬戸内海沿岸'),
  fukuokaSetoInlandSea(710, '福岡県瀬戸内海沿岸'),
  fukuokaSeaOfJapan(711, '福岡県日本海沿岸'),
  ariakeYatsushiroSea(712, '有明・八代海'),
  sagaNorth(720, '佐賀県北部'),
  nagasakiWest(730, '長崎県西方'),
  ikiTsushima(731, '壱岐・対馬'),
  kumamotoAmakusaNada(740, '熊本県天草灘沿岸'),
  oitaSetoInlandSea(750, '大分県瀬戸内海沿岸'),
  oitaBungoChannel(751, '大分県豊後水道沿岸'),
  miyazaki(760, '宮崎県'),
  kagoshimaEast(770, '鹿児島県東部'),
  tanegashimaYakushima(771, '種子島・屋久島地方'),
  amamiTokara(772, '奄美群島・トカラ列島'),
  kagoshimaWest(773, '鹿児島県西部'),
  yamaguchi(781, '山口県'),
  fukuoka(782, '福岡県'),
  saga(783, '佐賀県'),
  nagasaki(784, '長崎県'),
  kumamoto(785, '熊本県'),
  oita(786, '大分県'),
  kagoshima(787, '鹿児島県'),
  kyushuEast(791, '九州地方東部'),
  kyushuWest(792, '九州地方西部'),
  satsunanIslands(793, '薩南諸島'),
  okinawaMainIsland(800, '沖縄本島地方'),
  daitoIslands(801, '大東島地方'),
  miyakoYaeyama(802, '宮古島・八重山地方'),
  okinawa(891, '沖縄県地方'),
  other(1000, 'その他の津波予報区')
  ;

  const JmaTsunamiForecastRegion(this.code, this.name);

  final int code;
  final String name;

  static JmaTsunamiForecastRegion fromCode(int code) =>
      values.firstWhere((e) => e.code == code);
}
