name: live_activity_util
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.11.0
  flutter: ^3.44.0

resolution: workspace

dev_dependencies:
  altive_lints: ^3.0.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
  test: ^1.29.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.5
  ffigen: ^20.1.1
  hooks: ^2.0.0
  native_toolchain_c: ^0.19.1
  objective_c: ^9.2.2
  path: ^1.9.1
