name: topo_map
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.3

dependencies:
  collection: ^1.17.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  topojson:
    path: ../topojson

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0


executables:
  topojsonconverter:
    script: bin/topo_json_converter.dart