// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsBackgroundLocationApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashBackgroundLocationApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsBackgroundLocationApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsBackgroundLocationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsBackgroundLocationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsBackgroundLocationApi(lhsKey, rhsKey) {
          if deepEqualsBackgroundLocationApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsBackgroundLocationApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashBackgroundLocationApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashBackgroundLocationApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashBackgroundLocationApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashBackgroundLocationApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashBackgroundLocationApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashBackgroundLocationApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum PendingLocationConsumer: Int {
  case deviceLocation = 0
  case appEffects = 1
}

enum HeadlessTaskResult: Int {
  case success = 0
  case retry = 1
  case terminalFailure = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct PendingLocationMessage: Hashable {
  var updateId: String
  var latitude: Double
  var longitude: Double
  var accuracy: Double
  var timestampMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PendingLocationMessage? {
    let updateId = pigeonVar_list[0] as! String
    let latitude = pigeonVar_list[1] as! Double
    let longitude = pigeonVar_list[2] as! Double
    let accuracy = pigeonVar_list[3] as! Double
    let timestampMillis = pigeonVar_list[4] as! Int64

    return PendingLocationMessage(
      updateId: updateId,
      latitude: latitude,
      longitude: longitude,
      accuracy: accuracy,
      timestampMillis: timestampMillis
    )
  }
  func toList() -> [Any?] {
    return [
      updateId,
      latitude,
      longitude,
      accuracy,
      timestampMillis,
    ]
  }
  static func == (lhs: PendingLocationMessage, rhs: PendingLocationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsBackgroundLocationApi(lhs.updateId, rhs.updateId) && deepEqualsBackgroundLocationApi(lhs.latitude, rhs.latitude) && deepEqualsBackgroundLocationApi(lhs.longitude, rhs.longitude) && deepEqualsBackgroundLocationApi(lhs.accuracy, rhs.accuracy) && deepEqualsBackgroundLocationApi(lhs.timestampMillis, rhs.timestampMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PendingLocationMessage")
    deepHashBackgroundLocationApi(value: updateId, hasher: &hasher)
    deepHashBackgroundLocationApi(value: latitude, hasher: &hasher)
    deepHashBackgroundLocationApi(value: longitude, hasher: &hasher)
    deepHashBackgroundLocationApi(value: accuracy, hasher: &hasher)
    deepHashBackgroundLocationApi(value: timestampMillis, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceLocationSyncLeaseMessage: Hashable {
  var leaseId: String
  var updateId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceLocationSyncLeaseMessage? {
    let leaseId = pigeonVar_list[0] as! String
    let updateId = pigeonVar_list[1] as! String

    return DeviceLocationSyncLeaseMessage(
      leaseId: leaseId,
      updateId: updateId
    )
  }
  func toList() -> [Any?] {
    return [
      leaseId,
      updateId,
    ]
  }
  static func == (lhs: DeviceLocationSyncLeaseMessage, rhs: DeviceLocationSyncLeaseMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsBackgroundLocationApi(lhs.leaseId, rhs.leaseId) && deepEqualsBackgroundLocationApi(lhs.updateId, rhs.updateId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceLocationSyncLeaseMessage")
    deepHashBackgroundLocationApi(value: leaseId, hasher: &hasher)
    deepHashBackgroundLocationApi(value: updateId, hasher: &hasher)
  }
}

private class BackgroundLocationApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PendingLocationConsumer(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HeadlessTaskResult(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PendingLocationMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return DeviceLocationSyncLeaseMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BackgroundLocationApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PendingLocationConsumer {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HeadlessTaskResult {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PendingLocationMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceLocationSyncLeaseMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BackgroundLocationApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BackgroundLocationApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BackgroundLocationApiPigeonCodecWriter(data: data)
  }
}

class BackgroundLocationApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BackgroundLocationApiPigeonCodec(readerWriter: BackgroundLocationApiPigeonCodecReaderWriter())
}

/// Flutter → Native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackgroundLocationHostApi {
  func initialize(callbackHandle: Int64) throws
  func startMonitoring() throws
  func stopMonitoring() throws
  func peekPendingLocation(consumer: PendingLocationConsumer) throws -> PendingLocationMessage?
  func acknowledgePendingLocation(updateId: String, consumer: PendingLocationConsumer) throws -> Bool
  func acquireDeviceLocationSyncLease(updateId: String, durationMillis: Int64) throws -> DeviceLocationSyncLeaseMessage?
  func isDeviceLocationSyncLeaseCurrent(leaseId: String, updateId: String) throws -> Bool
  func releaseDeviceLocationSyncLease(leaseId: String) throws
  func getActiveHeadlessTaskId() throws -> String?
  func completeHeadlessTask(updateId: String, result: HeadlessTaskResult) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackgroundLocationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BackgroundLocationApiPigeonCodec.shared }
  /// Sets up an instance of `BackgroundLocationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackgroundLocationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let callbackHandleArg = args[0] as! Int64
        do {
          try api.initialize(callbackHandle: callbackHandleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let startMonitoringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.startMonitoring\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startMonitoringChannel.setMessageHandler { _, reply in
        do {
          try api.startMonitoring()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startMonitoringChannel.setMessageHandler(nil)
    }
    let stopMonitoringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.stopMonitoring\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMonitoringChannel.setMessageHandler { _, reply in
        do {
          try api.stopMonitoring()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopMonitoringChannel.setMessageHandler(nil)
    }
    let peekPendingLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.peekPendingLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      peekPendingLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let consumerArg = args[0] as! PendingLocationConsumer
        do {
          let result = try api.peekPendingLocation(consumer: consumerArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      peekPendingLocationChannel.setMessageHandler(nil)
    }
    let acknowledgePendingLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.acknowledgePendingLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgePendingLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateIdArg = args[0] as! String
        let consumerArg = args[1] as! PendingLocationConsumer
        do {
          let result = try api.acknowledgePendingLocation(updateId: updateIdArg, consumer: consumerArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      acknowledgePendingLocationChannel.setMessageHandler(nil)
    }
    let acquireDeviceLocationSyncLeaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.acquireDeviceLocationSyncLease\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acquireDeviceLocationSyncLeaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateIdArg = args[0] as! String
        let durationMillisArg = args[1] as! Int64
        do {
          let result = try api.acquireDeviceLocationSyncLease(updateId: updateIdArg, durationMillis: durationMillisArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      acquireDeviceLocationSyncLeaseChannel.setMessageHandler(nil)
    }
    let isDeviceLocationSyncLeaseCurrentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.isDeviceLocationSyncLeaseCurrent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDeviceLocationSyncLeaseCurrentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let leaseIdArg = args[0] as! String
        let updateIdArg = args[1] as! String
        do {
          let result = try api.isDeviceLocationSyncLeaseCurrent(leaseId: leaseIdArg, updateId: updateIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDeviceLocationSyncLeaseCurrentChannel.setMessageHandler(nil)
    }
    let releaseDeviceLocationSyncLeaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.releaseDeviceLocationSyncLease\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseDeviceLocationSyncLeaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let leaseIdArg = args[0] as! String
        do {
          try api.releaseDeviceLocationSyncLease(leaseId: leaseIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseDeviceLocationSyncLeaseChannel.setMessageHandler(nil)
    }
    let getActiveHeadlessTaskIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.getActiveHeadlessTaskId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getActiveHeadlessTaskIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getActiveHeadlessTaskId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getActiveHeadlessTaskIdChannel.setMessageHandler(nil)
    }
    let completeHeadlessTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.background_location_tracker.BackgroundLocationHostApi.completeHeadlessTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      completeHeadlessTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateIdArg = args[0] as! String
        let resultArg = args[1] as! HeadlessTaskResult
        do {
          try api.completeHeadlessTask(updateId: updateIdArg, result: resultArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      completeHeadlessTaskChannel.setMessageHandler(nil)
    }
  }
}
/// Native → Flutter (Path A: engine running)
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BackgroundLocationFlutterApiProtocol {
  func onLocationUpdate(location locationArg: PendingLocationMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BackgroundLocationFlutterApi: BackgroundLocationFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BackgroundLocationApiPigeonCodec {
    return BackgroundLocationApiPigeonCodec.shared
  }
  func onLocationUpdate(location locationArg: PendingLocationMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.background_location_tracker.BackgroundLocationFlutterApi.onLocationUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([locationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
