# TODO: If https://github.com/dependabot/dependabot-core/issues/2166 is resolved, this workflow becomes unnecessary.
name: Upgrade Flutter Dependencies

on:
  schedule:
    - cron: '0 1 * * 5' # every Friday, 01:00 (UTC)
  workflow_dispatch:

jobs:
  upgrade_flutter_dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - run: flutter doctor -v
      - run: flutter pub upgrade --null-safety # See: https://dart.dev/tools/pub/cmd/pub-upgrade#--null-safety

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets. GITHUB_TOKEN }} # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          commit-message: '[Scheduled] `flutter pub upgrade --null-safety`'
          title: '[Scheduled] `flutter pub upgrade --null-safety`'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          delete-branch: true
          labels: dependencies
