version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # Monday at 9am JST
      timezone: "Asia/Tokyo"
      time: "09:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directories:
      - /
      - /app
      - /packages/*
    schedule:
      interval: "daily"
      # Monday at 9am JST
      timezone: "Asia/Tokyo"
      time: "09:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/app/android"
    schedule:
      interval: "daily"
      # Monday at 9am JST
      timezone: "Asia/Tokyo"
      time: "09:00"
  - package-ecosystem: "bundler"
    directory: "/app/ios"
    schedule:
      interval: "daily"
      # Monday at 9am JST
      timezone: "Asia/Tokyo"
      time: "09:00"
