name: jma_parameter_types
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: 3.8.1

resolution: workspace

dependencies:
  protobuf: ^4.0.0

dev_dependencies:
  altive_lints: ^1.16.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
