name: jma_parameter_types
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.3.0-174.3.beta

dependencies:
  protobuf: ^3.1.0

dev_dependencies:
  pedantic_mono: ^1.23.0
