include: package:eqmonitor_lints/analysis_options.yaml
analyzer:
  errors:
    avoid_implementing_value_types: ignore
    avoid_print: ignore
    document_ignores: ignore
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    unnecessary_async: ignore
    unnecessary_cast: ignore
  exclude:
    - "**/DerivedData/**"
    - "**/build/**"
    - "build/**"
    - third_party/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

plugins:
  eqmonitor_lints_plugin:
    path: tools/eqmonitor_lints_plugin
    diagnostics:
      avoid_stateful_widget: true
      avoid_null_assertion_operator: true
      avoid_top_level_functions: true
      avoid_print: true
      avoid_eqmonitor_api_in_ui: true
      avoid_mixed_declaration_categories: true

linter:
  rules:
    # Introduced in Dart 3.13
    # See: https://dart.dev/blog/announcing-dart-3-13#primary-constructors
    empty_container_bodies: true
    initialize_in_field_declaration: true
    unnecessary_const_in_enum_constructor: true
    unnecessary_primary_constructor_body: true
    unnecessary_type_name_in_constructor: true
    use_declaring_parameters: true

formatter:
  trailing_commas: preserve
