include: package:eqmonitor_lints/analysis_options.yaml
analyzer:
  errors:
    avoid_implementing_value_types: ignore
    avoid_print: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    unnecessary_async: ignore
  exclude:
    - "**/DerivedData/**"
    - "**/build/**"
    - "build/**"

plugins:
  eqmonitor_lints_plugin:
    path: tools/eqmonitor_lints_plugin
    diagnostics:
      avoid_stateful_widget: true
      avoid_null_assertion_operator: true
      avoid_top_level_functions: true
      avoid_print: true
      avoid_eqmonitor_api_in_ui: true
      avoid_mixed_declaration_categories: true
