name: eqmonitor
repository: https://github.com/YumNumm/EQMonitor
sdkPath: .fvm/flutter_sdk

command:
  version:
    includeCommitId: true
    linkToCommits: true

scripts:
  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  build_runner:
    exec: flutter pub run build_runner build -d
    packageFilters:
      dependsOn: build_runner
  format:
    exec: $PWD/util/shell/format.sh

packages:
  - .
  - packages/*
