min_version = "2025.11.11"
experimental_monorepo_root = true

[tools]
"aqua:suzuki-shunsuke/tfcmt" = "4.14.12"
biome = "latest"
flutter = "3.38.3-stable"
"gem:cocoapods" = "latest"
java = "17"
node = "lts"
"pipx:codemagic-cli-tools" = "0.62.1"
pnpm = "latest"
ruby = "latest"
tflint = "0.59.1"
uv = "latest"
websocat = "1.14.0"
xcbeautify = "latest"
gcloud = "latest"
terraform = "latest"
python = "latest"
firebase = "latest"
yq = "latest"
actionlint = "latest"
pinact = "latest"

[settings]
lockfile = true
experimental = true
plugin_autoupdate_last_check_duration = "1 week"
