min_version = "2025.11.11"
experimental_monorepo_root = true

[tools]
"aqua:suzuki-shunsuke/tfcmt" = "latest"
biome = "latest"
flutter = "3.41.4-stable"
java = "17"
node = "lts"
"pipx:codemagic-cli-tools" = "latest"
pnpm = "latest"
tflint = "latest"
uv = "latest"
websocat = "latest"
xcbeautify = "latest"
gcloud = "latest"
terraform = "latest"
python = "latest"
firebase = "latest"
yq = "latest"
actionlint = "latest"
pinact = "latest"
swiftformat = "latest"
shellcheck = "latest"
"github:YumNumm/google-play-cli" = "latest"

[settings]
lockfile = true
experimental = true
plugin_autoupdate_last_check_duration = "1 week"
