name: eqmonitor_workspace
description: The workspace for the EQMonitor project.
environment:
  sdk: 3.8.1
  flutter: 3.32.1
workspace:
  - app
  - packages/_base
  - packages/eqapi_client
  - packages/eqapi_types
  - packages/eqmonitor_lints
  - packages/extensions
  - packages/jma_code_table_converter_internal
  - packages/jma_code_table_types
  - packages/jma_map
  - packages/jma_parameter_api_client
  - packages/jma_parameter_converter_internal
  - packages/jma_parameter_types
  - packages/kyoshin_observation_point_converter_internal
  - packages/kyoshin_observation_point_types
  - packages/lat_lng
  - packages/earthquake_replay
  - packages/msgpack_dart
  - packages/kyoshin_monitor_api
  - packages/kyoshin_monitor_image_parser
  # <ADD_PACKAGE_HERE>
dependencies:
  melos: ^7.0.0-dev.8
dependency_overrides:
  freezed_annotation: ^3.0.0
  maplibre_gl:
    git:
      url: https://github.com/YumNumm/flutter-maplibre-gl.git
      ref: 2b653ca28184004db852f20cf91b7a068760103c
      path: maplibre_gl
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/YumNumm/flutter-maplibre-gl.git
      ref: 2b653ca28184004db852f20cf91b7a068760103c
      path: maplibre_gl_platform_interface
  maplibre_gl_web:
    git:
      url: https://github.com/YumNumm/flutter-maplibre-gl.git
      ref: 2b653ca28184004db852f20cf91b7a068760103c
      path: maplibre_gl_web
  # maplibre:
  #   git:
  #     url: https://github.com/YumNumm/flutter-maplibre.git
  #     ref: c206212edf54c9331e3b2d040f256b4dbb08106f
  protobuf: ^4.0.0
melos:
  repository: https://github.com/YumNumm/EQMonitor
  command:
    version:
      linkToCommits: true
    bootstrap:
      runPubGetInParallel: false
      environment:
        sdk: 3.8.1
        flutter: 3.32.1
  scripts:
    analyze:
      run: |
        melos exec -c 1 -- \
          dart analyze . --fatal-infos
      description: |
        Run `dart analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.
    generate:
      run: melos run generate:dart && melos run generate:flutter
      description: Build all generated files for Dart & Flutter packages in this project.
    rebuild:
      description: build_runner を使用してコードを生成します。
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
    upgrade:
      description: dart pub のバージョンアップを実施します。
      run: dart pub upgrade
      exec:
        concurrency: 1
        orderDependents: true
    upgrade:major:
      description: dart pub のメジャーバージョンアップを実施します。
      run: dart pub upgrade --major-versions
      exec:
        concurrency: 1
        orderDependents: true
    clean-all:
      run: melos clean &&  melos exec "flutter clean"
    # dependsOn で or 条件で指定することができないため
    # スクリプトを Flutter と Dart に分けている
    test:
      description: すべてのパッケージのテストを実行します。
      steps:
        - test:flutter
        - test:dart
    test:flutter:
      description: Flutter パッケージのテストを実行します。
      run: flutter test
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: flutter_test
        dirExists: test
    test:dart:
      description: Dart パッケージのテストを実行します。
      run: dart test
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: test
        dirExists: test
    # dependsOn で or 条件で指定することができないため
    # スクリプトを Flutter と Dart に分けている
    report:test:
      description: すべてのパッケージのテストレポートを生成します。
      steps:
        - report:test:flutter
        - report:test:dart
    report:test:flutter:
      description: Flutter パッケージのテストレポートを生成します。
      run: flutter test --no-pub --machine > test_report.log
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: flutter_test
        dirExists: test
    report:test:dart:
      description: Dart パッケージのテストレポートを生成します。
      run: dart test --file-reporter="json:test_report.log"
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: test
        dirExists: test
    ci:report:custom_lint:
      description: CI 環境で custom_lint のレポートを生成します。
      exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
      packageFilters:
        dependsOn: custom_lint
  ide:
    intellij:
      enabled: false
