services:
  dmdata-websocket-proxy:
    image: registry.yumnumm.dev/eqmonitor-server/dmdata-websocket-proxy:latest
    build:
      context: .
      dockerfile: services/dmdata-websocket-proxy/Dockerfile
      args:
        NODE_VERSION: 23
        PROJECT: dmdata-websocket-proxy
        PORT: 3000
    environment:
      - DMDATA_WS_PROXY_PORT=3000
      - DMDATA_WS_PROXY_HOST=0.0.0.0
      - DMDATA_WS_PROXY_PATH=/ws
      - DMDATA_WS_PROXY_LOKI_HOST=loki.yumnumm.dev
    env_file:
      - .env.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 3000:3000

  eqapi-websocket-proxy:
    image: registry.yumnumm.dev/eqmonitor-server/eqapi-websocket-proxy:latest
    build:
      context: .
      dockerfile: services/eqapi-websocket-proxy/Dockerfile
      args:
        NODE_VERSION: 23
        PROJECT: eqapi-websocket-proxy
    environment:
      - DMDATA_WS_URL=ws://dmdata-websocket-proxy:3000/ws
    depends_on:
      - dmdata-websocket-proxy
    ports:
      - 3001:3000
    env_file:
      - .env.yaml

  # notification-service:
  #   image: registry.yumnumm.dev/eqmonitor-server/notification-service:latest
  #   build:
  #     context: .
  #     dockerfile: services/notification-service/Dockerfile
  #     args:
  #       NODE_VERSION: 23
  #       PROJECT: dmdata-websocket-proxy
  #       PORT: 3000
  #   environment:
  #     - DMDATA_WS_URL=ws://dmdata-websocket-proxy:3000/ws
  #   depends_on:
  #     - dmdata-websocket-proxy
  #   env_file:
  #     - .env.yaml
