analyzer:
  errors:
    avoid_implementing_value_types: ignore
    avoid_print: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    unnecessary_async: ignore
    unnecessary_cast: ignore
  exclude:
    - "**/DerivedData/**"
    - "**/build/**"
    - "build/**"
    - "lib/src/**"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
