targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - type=warning
            - duplicate_ignore
            - unused_element_parameter
global_options:
  freezed:
    runs_before:
      - json_serializable
