swagger_parser:
  schema_path: openapi/openapi.json
  output_directory: lib
  language: dart
  json_serializer: freezed
  default_content_type: "application/json"
  extras_parameter_by_default: false
  add_openapi_metadata: false
  dio_options_parameter_by_default: false
  root_client: true
  root_client_name: ApiClient
  export_file: true
  put_in_folder: false
  put_clients_in_folder: true
  merge_clients: false
  client_postfix: ApiClient
  path_method_name: true
  enums_to_json: true
  enums_parent_prefix: true
  unknown_enum_value: false
  mark_files_as_generated: true
  original_http_response: true
  use_freezed3: true
  use_multipart_file: true
  generate_urls_constants: true
  include_tags:
    - Anonymous
    - Default
  include_if_null: true
  infer_required_from_nullable: true
  use_flutter_compute: false
