name: jma_code_table_types
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  protobuf: ^4.0.0

dev_dependencies:
  eqmonitor_lints:
    path: ../eqmonitor_lints
  altive_lints: ^1.16.0
