import 'package:eqmonitor_map/eqmonitor_map.dart';
import 'package:flutter/widgets.dart';

/// Checked-in literals captured from the current MapLibre camera API.
///
/// Source versions:
/// - Flutter `maplibre` 0.3.5, git commit
///   `eecbdda1f7590d952449e8e4b309e09b04c30f9a`.
/// - Its WebView backend declares `maplibre-gl@^5.15.0`; capture pinned the
///   implementation to `maplibre-gl@5.15.0`.
///
/// Coordinate convention is `[[west, south], [east, north]]` in WGS84
/// degrees. Viewport and padding use logical CSS pixels, with padding ordered
/// as top/right/bottom/left. An antimeridian interval has `west > east`.
///
/// Capture commands (2026-08-24):
/// ```sh
/// npm install --prefix /private/tmp/eqmonitor-maplibre-fixture \
///   maplibre-gl@5.15.0 tsx@4.20.6
/// /private/tmp/eqmonitor-maplibre-fixture/node_modules/.bin/tsx \
///   /private/tmp/eqmonitor-maplibre-fixture/capture.ts
/// ```
/// `capture.ts` instantiated MapLibre's `MercatorTransform`, called `resize`
/// with each literal viewport, and invoked `Camera.cameraForBounds` with the
/// literal bounds/padding below. These expected values are not generated by
/// EQMonitor's fitter.
const mapLibreFitBoundsFixtures = <MapLibreFitBoundsFixture>[
  MapLibreFitBoundsFixture(
    name: 'normal Japan bounds',
    bounds: MapCameraBounds(west: 130, south: 30, east: 145, north: 46),
    viewportLogicalSize: Size(800, 600),
    padding: EdgeInsets.all(40),
    expectedCamera: MapCamera(
      centerLongitude: 137.50000000000006,
      centerLatitude: 38.44125695562542,
      zoom: 4.159991856918603,
    ),
  ),
  MapLibreFitBoundsFixture(
    name: 'antimeridian bounds',
    bounds: MapCameraBounds(west: 170, south: -10, east: -170, north: 10),
    viewportLogicalSize: Size(800, 600),
    padding: EdgeInsets.fromLTRB(32, 24, 32, 24),
    expectedCamera: MapCamera(
      centerLongitude: 179.99999999999994,
      centerLatitude: 0,
      zoom: 4.271087495686686,
    ),
  ),
  MapLibreFitBoundsFixture(
    name: 'asymmetric padding',
    bounds: MapCameraBounds(west: -133, south: 16, east: -68, north: 50),
    viewportLogicalSize: Size(1024, 768),
    padding: EdgeInsets.fromLTRB(25, 10, 75, 50),
    expectedCamera: MapCamera(
      centerLongitude: -98.74134199134198,
      centerLatitude: 33.552575960414245,
      zoom: 3.321234324717278,
    ),
  ),
  MapLibreFitBoundsFixture(
    name: 'wide resized viewport',
    bounds: MapCameraBounds(west: 130, south: 30, east: 145, north: 46),
    viewportLogicalSize: Size(1200, 400),
    padding: EdgeInsets.all(40),
    expectedCamera: MapCamera(
      centerLongitude: 137.5,
      centerLatitude: 38.44125695562542,
      zoom: 3.4595521387775117,
    ),
  ),
];

const mapLibreMaxZoomClampFixture = MapLibreFitBoundsFixture(
  name: 'max zoom clamp',
  bounds: MapCameraBounds(
    west: 139.7,
    south: 35.6,
    east: 139.71,
    north: 35.61,
  ),
  viewportLogicalSize: Size(800, 600),
  padding: EdgeInsets.zero,
  expectedCamera: MapCamera(
    centerLongitude: 139.70499999999998,
    centerLatitude: 35.60500015622043,
    zoom: 12,
  ),
  maxZoom: 12,
);

final class MapLibreFitBoundsFixture {
  const MapLibreFitBoundsFixture({
    required this.name,
    required this.bounds,
    required this.viewportLogicalSize,
    required this.padding,
    required this.expectedCamera,
    this.minZoom = 0,
    this.maxZoom = 20,
  });

  final String name;
  final MapCameraBounds bounds;
  final Size viewportLogicalSize;
  final EdgeInsets padding;
  final MapCamera expectedCamera;
  final double minZoom;
  final double maxZoom;
}
