name: fnet_api_client
description: F-net earthquake catalog API client
version: 1.0.0

publish_to: "none"

environment:
  sdk: 3.10.0

resolution: workspace

dependencies:
  dio: ^5.9.0
  fnet_types:
    path: ../fnet_types
  intl: ^0.20.2
  retrofit: ^4.9.0

dev_dependencies:
  altive_lints: ^1.14.1
  build_runner: ^2.7.1
  eqmonitor_lints:
    path: ../eqmonitor_lints
  http_mock_adapter: ^0.6.1
  retrofit_generator: ^10.0.0
  test: ^1.26.2
