# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  language:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    duplicate_ignore: ignore

linter:
  rules:
    always_use_package_imports: true
    lines_longer_than_80_chars: false
