name: eqmonitor
description: An earthquake monitoring Application
publish_to: "none"

version: 3.0.0

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

resolution: workspace

dependency_overrides:
  flutter_inappwebview: 6.2.0-beta.3
  maplibre:
    git:
      url: https://github.com/YumNumm/flutter-maplibre.git
      ref: 1d32edcc4ea158b7bc1e43afa88e5086cd11f958
      path: packages/maplibre
  maplibre_android:
    git:
      url: https://github.com/YumNumm/flutter-maplibre.git
      ref: 1d32edcc4ea158b7bc1e43afa88e5086cd11f958
      path: packages/maplibre_android
  maplibre_ios:
    git:
      url: https://github.com/YumNumm/flutter-maplibre.git
      ref: 1d32edcc4ea158b7bc1e43afa88e5086cd11f958
      path: packages/maplibre_ios
dependencies:
  app_settings: ^7.0.0
  better_auth_api_client:
    path: ../packages/better_auth_api_client
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  collection: ^1.19.1
  core:
    path: ../packages/core
  crypto: ^3.0.6
  cue: ^0.1.4
  dart_azarashi:
    path: ../packages/dart_azarashi
  device_info_plus: ^12.1.0
  dio: ^5.8.0+1
  dynamic_color: ^1.7.0
  earthquake_replay:
    path: ../packages/earthquake_replay
  eqmonitor_api:
    path: ../packages/eqmonitor_api
  extensions:
    path: ../packages/extensions
  file_picker: ^11.0.2
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.2
  firebase_app_installations: ^0.4.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker.git
      ref: e9b124896076991fa077f62bdbab3df1a26149d7
  flutter_hooks: ^0.21.2
  flutter_html: ^3.0.0
  flutter_local_notifications: ^21.0.0-dev.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.5
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_sticky_header: ^0.8.0
  flutter_test:
    sdk: flutter
  flutter_timezone: ^5.0.1
  flutter_udid:
    git:
      url: https://github.com/YumNumm/flutter_udid.git
      ref: d8f72a1e9e09a9f76f4e5051f167b31c5e2af52e
  freezed_annotation: ^3.0.0
  geobase: ^1.5.0
  geodata: ^1.3.0
  geolocator: ^14.0.1
  go_router: ^17.0.0
  google_api_availability: ^5.0.1
  google_fonts: ^8.0.2
  google_sign_in: ^7.2.0
  hooks_riverpod: ^3.0.3
  image: ^4.4.0
  in_app_review: ^2.0.10
  intl: ^0.20.2
  jma_code_table_types:
    path: ../packages/jma_code_table_types
  jma_map:
    path: ../packages/jma_map
  jma_parameter_types:
    path: ../packages/jma_parameter_types
  json_annotation: ^4.11.0
  kyoshin_monitor_api:
    path: ../packages/kyoshin_monitor_api
  kyoshin_monitor_image_parser:
    path: ../packages/kyoshin_monitor_image_parser
  kyoshin_observation_point_types:
    path: ../packages/kyoshin_observation_point_types
  lat_lng:
    path: ../packages/lat_lng
  latlong2: ^0.9.1
  libserialport_plus: ^0.1.0
  live_activity_util:
    path: ../packages/live_activity_util
  maplibre: ^0.3.5
  nied_api_client:
    path: ../packages/nied_api_client
  ntp: ^2.0.0
  objective_c: ^9.2.2
  package_info_plus: ^9.0.0
  paging_view: ^2.8.1
  path_provider: ^2.1.5
  purchases_flutter: ^10.0.1
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.0
  screenshot: 3.0.0
  share_plus: ^12.0.0
  shared_preferences: ^2.3.3
  sheet:
    git:
      url: https://github.com/YumNumm/modal_bottom_sheet.git
      ref: main
      path: sheet
  soft_edge_blur: ^0.1.3
  synchronized: ^3.3.0
  talker_dio_logger: ^5.0.0
  talker_flutter: ^5.0.0
  timezone: ^0.11.0
  upgrader: ^13.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  version: ^3.0.2
  web_socket_client: ^0.2.1

dev_dependencies:
  altive_lints: ^2.1.0
  build_runner: ^2.4.13
  eqmonitor_lints:
    path: ../packages/eqmonitor_lints
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.8.0
  freezed: ^3.0.6
  go_router_builder: ^4.0.1
  json_serializable: ^6.9.0
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.0.3
  test: ^1.29.0

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    image: true
    flutter_svg: true

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true
  assets:
    - assets/
    - assets/map/
    - assets/images/
    - assets/images/theme/
    - assets/images/map/
    - assets/fonts/
    - assets/docs/
    - assets/parameter/

  fonts:
    - family: NotoSansJP
      fonts:
        # - asset: assets/fonts/NotoSansJP-Regular.ttf
        # weight: 400
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.ttf
          weight: 700
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMono/NotoSansMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansMono/NotoSansMono-Bold.ttf
          weight: 700
