name: _base
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.14.0-29.0.dev
  flutter: ^3.47.0-1.0.pre-97

resolution: workspace

dev_dependencies:
  eqmonitor_lints:
    path: ../eqmonitor_lints
  test: ^1.29.0
