name: _base
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

resolution: workspace

dev_dependencies:
  altive_lints: ^1.14.1
  eqmonitor_lints:
    path: ../eqmonitor_lints
