// Generated by Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.109.103 clang-1700.0.13.2)
#ifndef MAPLIBRE_IOS_SWIFT_H
#define MAPLIBRE_IOS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MapLibre;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="maplibre_ios",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC12maplibre_ios22CoordinateBoundsStruct")
@interface CoordinateBoundsStruct : NSObject
@property (nonatomic) double minLatitude;
@property (nonatomic) double minLongitude;
@property (nonatomic) double maxLatitude;
@property (nonatomic) double maxLongitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithMinLatitude:(double)minLatitude minLongitude:(double)minLongitude maxLatitude:(double)maxLatitude maxLongitude:(double)maxLongitude OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12maplibre_ios7Helpers")
@interface Helpers : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MLNMapView;
@class MLNStyleLayer;
@class NSString;
/// レイヤーを管理するクラス
SWIFT_CLASS("_TtC12maplibre_ios12LayerManager")
@interface LayerManager : NSObject
/// 初期化
/// \param mapView MapLibreのマップビュー
///
- (nonnull instancetype)initWithMapView:(MLNMapView * _Nonnull)mapView OBJC_DESIGNATED_INITIALIZER;
/// レイヤーを追加する
/// \param layer 追加するレイヤー
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addLayer:(MLNStyleLayer * _Nonnull)layer SWIFT_WARN_UNUSED_RESULT;
/// レイヤーを指定したレイヤーの上に追加する
/// \param layer 追加するレイヤー
///
/// \param above このレイヤーの上に追加する
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addLayer:(MLNStyleLayer * _Nonnull)layer aboveLayerId:(NSString * _Nonnull)aboveLayerId SWIFT_WARN_UNUSED_RESULT;
/// レイヤーを指定したレイヤーの下に追加する
/// \param layer 追加するレイヤー
///
/// \param below このレイヤーの下に追加する
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addLayer:(MLNStyleLayer * _Nonnull)layer belowLayerId:(NSString * _Nonnull)belowLayerId SWIFT_WARN_UNUSED_RESULT;
/// レイヤーを削除する
/// \param layerId 削除するレイヤーのID
///
///
/// returns:
/// 削除が成功したかどうか
- (BOOL)removeLayerWithLayerId:(NSString * _Nonnull)layerId SWIFT_WARN_UNUSED_RESULT;
/// レイヤーを取得する
/// \param layerId レイヤーのID
///
///
/// returns:
/// レイヤー（見つからない場合はnil）
- (MLNStyleLayer * _Nullable)getLayerWithLayerId:(NSString * _Nonnull)layerId SWIFT_WARN_UNUSED_RESULT;
/// レイヤーの表示・非表示を設定する
/// \param layerId レイヤーのID
///
/// \param visible 表示する場合はtrue、非表示にする場合はfalse
///
///
/// returns:
/// 設定が成功したかどうか
- (BOOL)setLayerVisibilityWithLayerId:(NSString * _Nonnull)layerId visible:(BOOL)visible SWIFT_WARN_UNUSED_RESULT;
/// レイヤーが存在するかどうかを確認する
/// \param layerId レイヤーのID
///
///
/// returns:
/// 存在する場合はtrue、存在しない場合はfalse
- (BOOL)isLayerExists:(NSString * _Nonnull)layerId SWIFT_WARN_UNUSED_RESULT;
/// 全てのレイヤーのIDを取得する
///
/// returns:
/// レイヤーIDの配列
- (NSArray<NSString *> * _Nonnull)getAllLayerIds SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PaddingStruct;
SWIFT_CLASS("_TtC12maplibre_ios9MapHelper")
@interface MapHelper : NSObject
+ (void)setVisibleCoordinateBoundsWithMapView:(MLNMapView * _Nonnull)mapView bounds:(CoordinateBoundsStruct * _Nonnull)bounds padding:(PaddingStruct * _Nonnull)padding animated:(BOOL)animated;
+ (void)setVisibleCoordinateBoundsWithMapView:(MLNMapView * _Nonnull)mapView bounds:(CoordinateBoundsStruct * _Nonnull)bounds paddingTop:(CGFloat)paddingTop paddingLeft:(CGFloat)paddingLeft paddingBottom:(CGFloat)paddingBottom paddingRight:(CGFloat)paddingRight animated:(BOOL)animated;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SourceManager;
SWIFT_CLASS("_TtC12maplibre_ios16MapLibreRegistry")
@interface MapLibreRegistry : NSObject
+ (NSDictionary<NSNumber *, id> * _Nonnull)getMapRegistry SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)getMapWithViewId:(int64_t)viewId SWIFT_WARN_UNUSED_RESULT;
+ (LayerManager * _Nullable)getLayerManagerWithViewId:(int64_t)viewId SWIFT_WARN_UNUSED_RESULT;
+ (SourceManager * _Nullable)getSourceManagerWithViewId:(int64_t)viewId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id _Nullable activity;)
+ (id _Nullable)activity SWIFT_WARN_UNUSED_RESULT;
+ (void)setActivity:(id _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id _Nullable context;)
+ (id _Nullable)context SWIFT_WARN_UNUSED_RESULT;
+ (void)setContext:(id _Nullable)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12maplibre_ios13PaddingStruct")
@interface PaddingStruct : NSObject
@property (nonatomic) double top;
@property (nonatomic) double left;
@property (nonatomic) double bottom;
@property (nonatomic) double right;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTop:(double)top left:(double)left bottom:(double)bottom right:(double)right OBJC_DESIGNATED_INITIALIZER;
@end

@class MLNSource;
@class MLNShapeSource;
@class UIImage;
@class NSData;
/// ソースを管理するクラス
SWIFT_CLASS("_TtC12maplibre_ios13SourceManager")
@interface SourceManager : NSObject
/// 初期化
/// \param mapView MapLibreのマップビュー
///
- (nonnull instancetype)initWithMapView:(MLNMapView * _Nonnull)mapView OBJC_DESIGNATED_INITIALIZER;
/// ソースを追加する
/// \param source 追加するソース
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addSource:(MLNSource * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
/// GeoJSONソースを作成して追加する
/// \param sourceId ソースID
///
/// \param geoJson GeoJSON形式のデータ
///
/// \param options ソースオプション
///
///
/// returns:
/// 追加が成功した場合はソース、失敗した場合はnil
- (MLNShapeSource * _Nullable)addGeoJSONSourceWithSourceId:(NSString * _Nonnull)sourceId geoJson:(NSDictionary<NSString *, id> * _Nonnull)geoJson options:(NSDictionary<MLNShapeSourceOption, id> * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
/// 空のGeoJSONソースを作成して追加する
/// \param sourceId ソースID
///
/// \param options ソースオプション
///
///
/// returns:
/// 追加が成功した場合はソース、失敗した場合はnil
- (MLNShapeSource * _Nullable)addEmptyGeoJSONSourceWithSourceId:(NSString * _Nonnull)sourceId options:(NSDictionary<MLNShapeSourceOption, id> * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
/// ソースを削除する
/// \param sourceId 削除するソースのID
///
///
/// returns:
/// 削除が成功したかどうか
- (BOOL)removeSourceWithSourceId:(NSString * _Nonnull)sourceId SWIFT_WARN_UNUSED_RESULT;
/// ソースを取得する
/// \param sourceId ソースのID
///
///
/// returns:
/// ソース（見つからない場合はnil）
- (MLNSource * _Nullable)getSourceWithSourceId:(NSString * _Nonnull)sourceId SWIFT_WARN_UNUSED_RESULT;
/// GeoJSONソースを取得する
/// \param sourceId ソースのID
///
///
/// returns:
/// GeoJSONソース（見つからない場合はnil）
- (MLNShapeSource * _Nullable)getGeoJSONSourceWithSourceId:(NSString * _Nonnull)sourceId SWIFT_WARN_UNUSED_RESULT;
/// GeoJSONソースを更新する
/// \param sourceId ソースのID
///
/// \param geoJson GeoJSON形式のデータ
///
///
/// returns:
/// 更新が成功したかどうか
- (BOOL)updateGeoJSONSourceWithSourceId:(NSString * _Nonnull)sourceId geoJson:(NSDictionary<NSString *, id> * _Nonnull)geoJson SWIFT_WARN_UNUSED_RESULT;
/// ソースが存在するかどうかを確認する
/// \param sourceId ソースのID
///
///
/// returns:
/// 存在する場合はtrue、存在しない場合はfalse
- (BOOL)sourceExists:(NSString * _Nonnull)sourceId SWIFT_WARN_UNUSED_RESULT;
/// 全てのソースのIDを取得する
///
/// returns:
/// ソースIDの配列
- (NSArray<NSString *> * _Nonnull)getAllSourceIds SWIFT_WARN_UNUSED_RESULT;
/// 画像を追加する
/// \param name 画像名
///
/// \param image 追加する画像
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addImageWithName:(NSString * _Nonnull)name image:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
/// 画像をデータから追加する
/// \param name 画像名
///
/// \param data 画像データ
///
///
/// returns:
/// 追加が成功したかどうか
- (BOOL)addImageFromDataWithName:(NSString * _Nonnull)name data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// GeoJSONソースをJSONオブジェクトで更新する
/// \param sourceId ソースID
///
/// \param geoJson GeoJSONオブジェクト
///
///
/// returns:
/// 更新が成功したかどうか
- (BOOL)updateGeoJSONSourceWithObjectWithSourceId:(NSString * _Nonnull)sourceId geoJson:(NSDictionary<NSString *, id> * _Nonnull)geoJson SWIFT_WARN_UNUSED_RESULT;
/// GeoJSONソースをJSON文字列で更新する
/// \param sourceId ソースID
///
/// \param geoJsonString GeoJSON文字列
///
///
/// returns:
/// 更新が成功したかどうか
- (BOOL)updateGeoJSONSourceWithStringWithSourceId:(NSString * _Nonnull)sourceId geoJsonString:(NSString * _Nonnull)geoJsonString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
