name: eqmonitor_lints

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

resolution: workspace

dependencies:
  altive_lints: ^1.18.0
  custom_lint: ^0.7.0
  flutter:
    sdk: flutter
  yumemi_lints: ^3.0.0
