name: eqmonitor_lints

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

resolution: workspace

dependencies:
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  flutter:
    sdk: flutter
  yumemi_lints: ^2.2.0
