name: kyoshin_monitor_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.6.1
  flutter: ^3.27.2

resolution: workspace

dependencies:
  args: ^2.4.2
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

dev_dependencies:
  altive_lints: ^1.14.1
  build_runner: ^2.4.14
  eqmonitor_lints:
    path: ../eqmonitor_lints
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.7
  test: ^1.25.2
