# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_push_certificate()
    increment_build_number(
      build_number: latest_testflight_build_number + 10,
      xcodeproj: "Runner.xcodeproj"
    )
    # Step 2 - Download provisioning profiles and certificates
    match(
      type: 'development',
      readonly: true,
    )

    # Step 3 - Build the project
    build_app(
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_method: "app-store",
    )

    # Step 4 - Upload the project
    changelog_from_git_commits()
    upload_to_testflight(
      ipa: "./Runner.ipa"
    )
  end

  lane :deploy do
    get_push_certificate()
    #increment_build_number(
    #  build_number: app_store_build_number + 1,
    #  xcodeproj: "Runner.xcodeproj"
    #)
    # Step 2 - Download provisioning profiles and certificates
    match(
      type: 'appstore',
      readonly: true,
    )

    # Step 3 - Build the project
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_method: "app-store",
    )

    # Step 4 - Upload the project
    changelog_from_git_commits()
    upload_to_app_store(
      ipa: "./Runner.ipa"
    )
  end
end
