name: pmtiles_renderer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # 地図関連
  flutter_map: ^6.0.0
  vector_map_tiles_mbtiles: ^1.1.0
  mbtiles: ^0.4.0
  # 状態管理
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # モデル
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # ルーティング
  go_router: ^14.6.2
  latlong2: ^0.9.1
  flutter_map_pmtiles: ^1.0.5
  vector_map_tiles_pmtiles: ^1.3.0
  vector_map_tiles: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # コード生成
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
