import 'dart:typed_data';

import 'package:freezed_annotation/freezed_annotation.dart';

part 'qzss_dc_report.freezed.dart';

/// Base class for all QZSS DC Report types.
@Freezed(copyWith: false)
sealed class QzssDcReport with _$QzssDcReport {
  const QzssDcReport._();

  /// Earthquake Early Warning report (緊急地震速報).
  const factory QzssDcReport.earthquakeEarlyWarning({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required String? longPeriodGroundMotionLowerLimit,
    required int longPeriodGroundMotionLowerLimitRaw,
    required String? longPeriodGroundMotionUpperLimit,
    required int longPeriodGroundMotionUpperLimitRaw,
    required List<String> notificationsOnDisasterPrevention,
    required List<int> notificationsOnDisasterPreventionRaw,
    required DateTime occurrenceTimeOfEarthquake,
    required String depthOfHypocenter,
    required int depthOfHypocenterRaw,
    required String magnitude,
    required int magnitudeRaw,
    required bool assumptive,
    required String seismicEpicenter,
    required int seismicEpicenterRaw,
    required String seismicIntensityLowerLimit,
    required int seismicIntensityLowerLimitRaw,
    required String seismicIntensityUpperLimit,
    required int seismicIntensityUpperLimitRaw,
    required List<String> eewForecastRegions,
    required List<int> eewForecastRegionsRaw,
  }) = QzssDcReportJmaEarthquakeEarlyWarning;

  /// Hypocenter report (震源).
  const factory QzssDcReport.hypocenter({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required List<String> notificationsOnDisasterPrevention,
    required List<int> notificationsOnDisasterPreventionRaw,
    required DateTime occurrenceTimeOfEarthquake,
    required String depthOfHypocenter,
    required int depthOfHypocenterRaw,
    required String magnitude,
    required int magnitudeRaw,
    required String seismicEpicenter,
    required int seismicEpicenterRaw,
    required HypocenterCoordinates coordinatesOfHypocenter,
  }) = QzssDcReportJmaHypocenter;

  /// Seismic Intensity report (震度).
  const factory QzssDcReport.seismicIntensity({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required DateTime occurrenceTimeOfEarthquake,
    required List<String> seismicIntensities,
    required List<int> seismicIntensitiesRaw,
    required List<String> prefectures,
    required List<int> prefecturesRaw,
  }) = QzssDcReportJmaSeismicIntensity;

  /// Nankai Trough Earthquake report (南海トラフ地震).
  const factory QzssDcReport.nankaiTroughEarthquake({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required String informationSerialCode,
    required int informationSerialCodeRaw,
    required Uint8List textInformation,
    required int pageNumber,
    required int totalPage,
    required bool completed,
  }) = QzssDcReportJmaNankaiTroughEarthquake;

  /// Tsunami report (津波).
  const factory QzssDcReport.tsunami({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required List<String> notificationsOnDisasterPrevention,
    required List<int> notificationsOnDisasterPreventionRaw,
    required String tsunamiWarningCode,
    required int tsunamiWarningCodeRaw,
    required List<DateTime?> expectedTsunamiArrivalTimes,
    required List<String> tsunamiHeights,
    required List<int> tsunamiHeightsRaw,
    required List<String> tsunamiForecastRegions,
    required List<int> tsunamiForecastRegionsRaw,
  }) = QzssDcReportJmaTsunami;

  /// Northwest Pacific Tsunami report (北西太平洋津波).
  const factory QzssDcReport.northwestPacificTsunami({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required String tsunamigenicPotentialEn,
    required int tsunamigenicPotentialRaw,
    required List<DateTime?> expectedTsunamiArrivalTimes,
    required List<String> tsunamiHeightsEn,
    required List<int> tsunamiHeightsRaw,
    required List<String> coastalRegionsEn,
    required List<int> coastalRegionsRaw,
  }) = QzssDcReportJmaNorthwestPacificTsunami;

  /// Volcano report (火山).
  const factory QzssDcReport.volcano({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required int ambiguityOfActivityTimeNo,
    required DateTime activityTime,
    required String volcanicWarningCode,
    required int volcanicWarningCodeRaw,
    required String volcanoName,
    required int volcanoNameRaw,
    required List<String> localGovernments,
    required List<int> localGovernmentsRaw,
  }) = QzssDcReportJmaVolcano;

  /// Ash Fall report (降灰).
  const factory QzssDcReport.ashFall({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required DateTime activityTime,
    required String ashFallWarningType,
    required int ashFallWarningTypeRaw,
    required String volcanoName,
    required int volcanoNameRaw,
    required List<int> expectedAshFallTimes,
    required List<String> ashFallWarningCodes,
    required List<int> ashFallWarningCodesRaw,
    required List<String> localGovernments,
    required List<int> localGovernmentsRaw,
  }) = QzssDcReportJmaAshFall;

  /// Weather report (気象).
  const factory QzssDcReport.weather({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required String weatherWarningState,
    required int weatherWarningStateRaw,
    required List<String> weatherRelatedDisasterSubCategories,
    required List<int> weatherRelatedDisasterSubCategoriesRaw,
    required List<String> weatherForecastRegions,
    required List<int> weatherForecastRegionsRaw,
  }) = QzssDcReportJmaWeather;

  /// Flood report (洪水).
  const factory QzssDcReport.flood({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required List<String> floodWarningLevels,
    required List<int> floodWarningLevelsRaw,
    required List<String> floodForecastRegions,
    required List<int> floodForecastRegionsRaw,
  }) = QzssDcReportJmaFlood;

  /// Typhoon report (台風).
  const factory QzssDcReport.typhoon({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required DateTime referenceTime,
    required String referenceTimeType,
    required int referenceTimeTypeRaw,
    required int elapsedTimeFromReferenceTime,
    required String typhoonNumber,
    required int typhoonNumberRaw,
    required String typhoonScaleCategory,
    required int typhoonScaleCategoryRaw,
    required String typhoonIntensityCategory,
    required int typhoonIntensityCategoryRaw,
    required TyphoonCoordinates coordinatesOfTyphoon,
    required String centralPressure,
    required int centralPressureRaw,
    required String maximumWindSpeed,
    required int maximumWindSpeedRaw,
    required String maximumGustWindSpeed,
    required int maximumGustWindSpeedRaw,
  }) = QzssDcReportJmaTyphoon;

  /// Marine report (海上).
  const factory QzssDcReport.marine({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required int version,
    required String reportClassification,
    required String reportClassificationEn,
    required int reportClassificationNo,
    required String disasterCategory,
    required String disasterCategoryEn,
    required int disasterCategoryNo,
    required DateTime reportTime,
    required String informationType,
    required String informationTypeEn,
    required int informationTypeNo,
    required List<String> marineWarningCodes,
    required List<int> marineWarningCodesRaw,
    required List<String> marineForecastRegions,
    required List<int> marineForecastRegionsRaw,
  }) = QzssDcReportJmaMarine;

  /// DCX Null message.
  const factory QzssDcReport.dcxNull({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxNullMsg;

  /// DCX Outside Japan message.
  const factory QzssDcReport.dcxOutsideJapan({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxOutsideJapan;

  /// DCX L-Alert message.
  const factory QzssDcReport.dcxLAlert({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxLAlert;

  /// DCX J-Alert message.
  const factory QzssDcReport.dcxJAlert({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxJAlert;

  /// DCX Municipality-Transmitted Information message.
  const factory QzssDcReport.dcxMTInfo({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxMTInfo;

  /// DCX Unknown message.
  const factory QzssDcReport.dcxUnknown({
    required String sentence,
    required Uint8List message,
    required String nmea,
    required String? messageHeader,
    required int? satelliteId,
    required int? satellitePrn,
    required Uint8List raw,
    required String preamble,
    required String messageType,
    required String dcxMessageType,
  }) = QzssDcxUnknown;
}

/// Coordinates of hypocenter.
@freezed
abstract class HypocenterCoordinates with _$HypocenterCoordinates {
  const factory HypocenterCoordinates({
    /// 0: North, 1: South
    required int latNs,
    required int latD,
    required int latM,
    required int latS,

    /// 0: East, 1: West
    required int lonEw,
    required int lonD,
    required int lonM,
    required int lonS,
  }) = _HypocenterCoordinates;
}

/// Coordinates of typhoon.
@freezed
abstract class TyphoonCoordinates with _$TyphoonCoordinates {
  const factory TyphoonCoordinates({
    /// 0: North, 1: South
    required int latNs,
    required int latD,
    required int latM,
    required int latS,

    /// 0: East, 1: West
    required int lonEw,
    required int lonD,
    required int lonM,
    required int lonS,
  }) = _TyphoonCoordinates;
}
