default_platform(:ios)

platform :ios do
  desc "Increment the build number"
  lane :setup_build_number do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: "NGL2W4BQP6",
      issuer_id: "fd4cca56-716b-4f03-8e44-de72a03453db",
      key_filepath: "./AuthKey_NGL2W4BQP6.p8"
    )
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Runner.xcodeproj",
    )
  end

  desc "Download the provisioning profiles"
  lane :download_provisioning_profiles do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: "NGL2W4BQP6",
      issuer_id: "fd4cca56-716b-4f03-8e44-de72a03453db",
      key_filepath: "./AuthKey_NGL2W4BQP6.p8"
    )
    match(
      readonly: true,
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: "NGL2W4BQP6",
      issuer_id: "fd4cca56-716b-4f03-8e44-de72a03453db",
      key_filepath: "./AuthKey_NGL2W4BQP6.p8"
    )
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Runner.xcodeproj",
    )

    match(
      type: "appstore",
      readonly: is_ci,
    )

    # Build the project
    build_app(
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
    )

    # Upload the project
    changelog = changelog_from_git_commits(
      date_format: "%Y-%m-%d",
      between: [last_git_tag, "HEAD"],
      pretty: "- %s",
      date_format: "short",
      match_lightweight_tag: false,
      merge_commit_filtering: "exclude_merges"
    )
    upload_to_testflight(
      ipa: "./Runner.ipa",
      changelog: changelog,
      skip_waiting_for_build_processing: ENV['CI'],
    )
  end

  desc "Push a new build to App Store Connect"
  lane :upload do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: "NGL2W4BQP6",
      issuer_id: "fd4cca56-716b-4f03-8e44-de72a03453db",
      key_filepath: "./AuthKey_NGL2W4BQP6.p8"
    )
    # Upload the project
    changelog = changelog_from_git_commits(
      date_format: "%Y-%m-%d",
      between: [last_git_tag, "HEAD"],
      pretty: "- %s",
      date_format: "short",
      match_lightweight_tag: false,
      merge_commit_filtering: "exclude_merges"
    )
    upload_to_testflight(
      ipa: "./Runner.ipa",
      changelog: changelog,
      skip_waiting_for_build_processing: ENV['CI'],
    )
  end
end
