name: earthquake_replay
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none"

environment:
  sdk: 3.8.1
  flutter: 3.32.1

resolution: workspace

dependencies:
  collection: ^1.19.0
  es_compression: ^2.0.13
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  msgpack_dart:
    path: ../msgpack_dart

dev_dependencies:
  altive_lints: ^1.14.1
  build_runner: ^2.4.14
  eqmonitor_lints:
    path: ../eqmonitor_lints
  freezed: ^2.5.7
  json_serializable: ^6.9.0
