# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates the shared EQMonitor lint configuration.
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:eqmonitor_lints/recommended.yaml

linter:
  # The lint rules applied to this project can be customized in the section
  # below. Prefer updating the shared configuration for repository-wide rules.
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
