name: assets_util_example
description: Minimal example used by jnigen to resolve Android Gradle deps.
publish_to: "none"

environment:
  sdk: ^3.11.0
  flutter: ^3.44.0

dependencies:
  assets_util:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
