name: jma_parameter_converter_internal
description: A sample command-line application.
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  jma_parameter_types:
    path: ../jma_parameter_types
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  collection: ^1.17.1
  file: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  pedantic_mono: ^1.23.0
