name: lat_lng
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  latlong2: ^0.10.1

dev_dependencies:
  altive_lints: ^3.0.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
  test: ^1.29.0
