name: lat_lng
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: ^3.14.0-29.0.dev

resolution: workspace

dependencies:
  latlong2: ^0.10.1

dev_dependencies:
  eqmonitor_lints:
    path: ../eqmonitor_lints
  test: ^1.29.0
