name: lat_lng
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: 3.9.2

resolution: workspace

dependencies:
  latlong2: ^0.9.0

dev_dependencies:
  altive_lints: ^1.16.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
