name: lat_lng
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: ^3.0.5

dependencies:
  latlong2: ^0.9.0

dev_dependencies:
  pedantic_mono: ^1.23.0
