// Mocks generated by Mockito 5.4.6 from annotations
// in eqmonitor/test/feature/map/data/service/map_automatic_focus_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i3;

import 'package:flutter/widgets.dart' as _i5;
import 'package:maplibre_platform_interface/maplibre_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMapOptions_0 extends _i1.SmartFake implements _i2.MapOptions {
  _FakeMapOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffset_1 extends _i1.SmartFake implements _i3.Offset {
  _FakeOffset_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeographic_2 extends _i1.SmartFake implements _i2.Geographic {
  _FakeGeographic_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMapCamera_3 extends _i1.SmartFake implements _i2.MapCamera {
  _FakeMapCamera_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLngLatBounds_4 extends _i1.SmartFake implements _i2.LngLatBounds {
  _FakeLngLatBounds_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MapController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapController extends _i1.Mock implements _i2.MapController {
  @override
  _i2.MapOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeMapOptions_0(this, Invocation.getter(#options)),
            returnValueForMissingStub: _FakeMapOptions_0(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.MapOptions);

  @override
  _i3.Offset toScreenLocation(_i2.Geographic? lngLat) =>
      (super.noSuchMethod(
            Invocation.method(#toScreenLocation, [lngLat]),
            returnValue: _FakeOffset_1(
              this,
              Invocation.method(#toScreenLocation, [lngLat]),
            ),
            returnValueForMissingStub: _FakeOffset_1(
              this,
              Invocation.method(#toScreenLocation, [lngLat]),
            ),
          )
          as _i3.Offset);

  @override
  _i2.Geographic toLngLat(_i3.Offset? screenLocation) =>
      (super.noSuchMethod(
            Invocation.method(#toLngLat, [screenLocation]),
            returnValue: _FakeGeographic_2(
              this,
              Invocation.method(#toLngLat, [screenLocation]),
            ),
            returnValueForMissingStub: _FakeGeographic_2(
              this,
              Invocation.method(#toLngLat, [screenLocation]),
            ),
          )
          as _i2.Geographic);

  @override
  List<_i3.Offset> toScreenLocations(List<_i2.Geographic>? lngLats) =>
      (super.noSuchMethod(
            Invocation.method(#toScreenLocations, [lngLats]),
            returnValue: <_i3.Offset>[],
            returnValueForMissingStub: <_i3.Offset>[],
          )
          as List<_i3.Offset>);

  @override
  List<_i2.Geographic> toLngLats(List<_i3.Offset>? screenLocations) =>
      (super.noSuchMethod(
            Invocation.method(#toLngLats, [screenLocations]),
            returnValue: <_i2.Geographic>[],
            returnValueForMissingStub: <_i2.Geographic>[],
          )
          as List<_i2.Geographic>);

  @override
  _i4.Future<void> moveCamera({
    _i2.Geographic? center,
    double? zoom,
    double? bearing,
    double? pitch,
    _i5.EdgeInsets? padding = _i5.EdgeInsets.zero,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveCamera, [], {
              #center: center,
              #zoom: zoom,
              #bearing: bearing,
              #pitch: pitch,
              #padding: padding,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> animateCamera({
    _i2.Geographic? center,
    double? zoom,
    double? bearing,
    double? pitch,
    Duration? nativeDuration = const Duration(seconds: 2),
    double? webSpeed = 1.2,
    Duration? webMaxDuration,
    _i5.EdgeInsets? padding = _i5.EdgeInsets.zero,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#animateCamera, [], {
              #center: center,
              #zoom: zoom,
              #bearing: bearing,
              #pitch: pitch,
              #nativeDuration: nativeDuration,
              #webSpeed: webSpeed,
              #webMaxDuration: webMaxDuration,
              #padding: padding,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> fitBounds({
    required _i2.LngLatBounds? bounds,
    double? bearing,
    double? pitch,
    Duration? nativeDuration = const Duration(seconds: 2),
    double? webSpeed = 1.2,
    Duration? webMaxDuration,
    _i3.Offset? offset = _i3.Offset.zero,
    double? webMaxZoom = 1.7976931348623157e+308,
    bool? webLinear = false,
    _i5.EdgeInsets? padding = _i5.EdgeInsets.zero,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fitBounds, [], {
              #bounds: bounds,
              #bearing: bearing,
              #pitch: pitch,
              #nativeDuration: nativeDuration,
              #webSpeed: webSpeed,
              #webMaxDuration: webMaxDuration,
              #offset: offset,
              #webMaxZoom: webMaxZoom,
              #webLinear: webLinear,
              #padding: padding,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.MapCamera getCamera() =>
      (super.noSuchMethod(
            Invocation.method(#getCamera, []),
            returnValue: _FakeMapCamera_3(
              this,
              Invocation.method(#getCamera, []),
            ),
            returnValueForMissingStub: _FakeMapCamera_3(
              this,
              Invocation.method(#getCamera, []),
            ),
          )
          as _i2.MapCamera);

  @override
  double getMetersPerPixelAtLatitude(double? latitude) =>
      (super.noSuchMethod(
            Invocation.method(#getMetersPerPixelAtLatitude, [latitude]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i2.LngLatBounds getVisibleRegion() =>
      (super.noSuchMethod(
            Invocation.method(#getVisibleRegion, []),
            returnValue: _FakeLngLatBounds_4(
              this,
              Invocation.method(#getVisibleRegion, []),
            ),
            returnValueForMissingStub: _FakeLngLatBounds_4(
              this,
              Invocation.method(#getVisibleRegion, []),
            ),
          )
          as _i2.LngLatBounds);

  @override
  List<_i2.QueriedLayer> queryLayers(_i3.Offset? screenLocation) =>
      (super.noSuchMethod(
            Invocation.method(#queryLayers, [screenLocation]),
            returnValue: <_i2.QueriedLayer>[],
            returnValueForMissingStub: <_i2.QueriedLayer>[],
          )
          as List<_i2.QueriedLayer>);

  @override
  List<_i2.RenderedFeature> featuresAtPoint(
    _i3.Offset? point, {
    List<String>? layerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#featuresAtPoint, [point], {#layerIds: layerIds}),
            returnValue: <_i2.RenderedFeature>[],
            returnValueForMissingStub: <_i2.RenderedFeature>[],
          )
          as List<_i2.RenderedFeature>);

  @override
  List<_i2.RenderedFeature> featuresInRect(
    _i3.Rect? rect, {
    List<String>? layerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#featuresInRect, [rect], {#layerIds: layerIds}),
            returnValue: <_i2.RenderedFeature>[],
            returnValueForMissingStub: <_i2.RenderedFeature>[],
          )
          as List<_i2.RenderedFeature>);

  @override
  _i4.Future<void> enableLocation({
    Duration? fastestInterval = const Duration(milliseconds: 750),
    Duration? maxWaitTime = const Duration(seconds: 1),
    bool? pulseFade = true,
    bool? accuracyAnimation = true,
    bool? compassAnimation = true,
    bool? pulse = true,
    _i2.BearingRenderMode? bearingRenderMode = _i2.BearingRenderMode.gps,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enableLocation, [], {
              #fastestInterval: fastestInterval,
              #maxWaitTime: maxWaitTime,
              #pulseFade: pulseFade,
              #accuracyAnimation: accuracyAnimation,
              #compassAnimation: compassAnimation,
              #pulse: pulse,
              #bearingRenderMode: bearingRenderMode,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackLocation({
    bool? trackLocation = true,
    _i2.BearingTrackMode? trackBearing = _i2.BearingTrackMode.gps,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackLocation, [], {
              #trackLocation: trackLocation,
              #trackBearing: trackBearing,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setStyle(String? style) => super.noSuchMethod(
    Invocation.method(#setStyle, [style]),
    returnValueForMissingStub: null,
  );
}
