name: jma_map
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.8.1

resolution: workspace

dependencies:
  collection: ^1.19.1
  geobase: ^1.5.0
  geodata: ^1.3.0
  protobuf: ^4.0.0

dev_dependencies:
  altive_lints: ^1.16.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
