name: eqapi_types
description: EQApi API Type Definitions
version: 1.0.1
publish_to: "none"

environment:
  sdk: 3.9.2

resolution: workspace


dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  lat_lng:
    path: ../lat_lng

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.6
  eqmonitor_lints:
    path: ../eqmonitor_lints
  freezed: ^3.0.6
  lints: ^5.0.0
  test: ^1.24.7
