include: package:eqmonitor_lints/analysis_options.yaml

analyzer:
  exclude:
    - "**/*"

custom_lint:
  rules:
    - prefer_clock_now: false
    - avoid_hardcoded_color: false
    - avoid_hardcoded_japanese: false
    - avoid_single_child: false
