name: kyoshin_observation_point_types
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  protobuf: ^6.0.0

dev_dependencies:
  altive_lints: ^2.1.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
