name: notification_setting_types

environment:
  sdk: ^3.5.4

dependencies:
  fixnum: ^1.1.1
  protobuf: ^3.1.0

dev_dependencies:
  eqmonitor_lints:
    path: ../eqmonitor_lints
  altive_lints: ^1.16.0
