name: notification_setting_types

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  fixnum: ^1.1.1
  protobuf: ^4.0.0

dev_dependencies:
  altive_lints: ^1.16.0
  eqmonitor_lints:
    path: ../eqmonitor_lints
