name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:
    # https://github.com/jdx/mise-action
    - name: Install Mise dependencies
      uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      with:
        install_args: "flutter"

    - name: Resolve dependencies
      shell: bash
      run: dart pub get

    # https://github.com/actions/cache
    - name: Cache pubspec dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          ~/.pub-cache
        key: pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pubspec-

    - name: Setup melos
      shell: bash
      run: |
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION

    - name: Resolve dependencies
      shell: bash
      run: dart run melos bootstrap
