name: "Setup macOS Environment"
description: "Setup macOS environment for Flutter to build iOS/macOS apps"

runs:
  using: "composite"
  steps:
      # https://github.com/maxim-lobanov/setup-xcode
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: 26.1

      - name: Show Xcode version
        shell: bash
        run: xcodebuild -version
