name: Arv Updator

#発火条件
on:
  #ソースをmainブランチにプッシュする時
  schedule:
    # Every Sunday at 00:00
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  DMDATA_ORIGIN: ${{secrets.DMDATA_ORIGIN}}
  DMDATA_KEY: ${{secrets.DMDATA_KEY}}
jobs:
  deploy:
    #ビルド環境
    runs-on: ubuntu-latest
    # タイムアウト時間を設定
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./util/arv

      - name: Generate
        run: python3 main.py
        working-directory: ./util/arv

      # 変更が発生した場合は main ブランチに向けてプルリクエストを作成
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ARV Update
          title: ARV Update
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: auto-format
          branch-suffix: short-commit-hash
