name: Assign author

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  auto-author:
    name: Assign author to PR
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      # https://github.com/technote-space/assign-author
      - name: Assign author to PR
        uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de # v3.0.3
