name: Automatic Flutter Update

on:
  schedule:
    # Every day at 9:00 JST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-has-flutter-update:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    outputs:
      has_update: ${{ steps.fetch-all-flutter-releases.outputs.has_update }}
      latest_version: ${{ steps.fetch-all-flutter-releases.outputs.latest_version }}
      current_version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action/config@0b792d004e2dfeda282a7af5c0609703658a9f8b # v3.1
        id: fvm-config-action
        # exposes: `steps.fvm-config-action.outputs.FLUTTER_VERSION`
        # exposes: `steps.fvm-config-action.outputs.FLUTTER_CHANNEL`

      - name: Fetch All Flutter Releases
        id: fetch-all-flutter-releases
        run: |
          LATEST_VERSION=$(curl -s "https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json" \
               | jq '.releases | map(select(.channel == "stable")) | map(.version)' | jq -r '.[0]')
          CURRENT_VERSION="${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}"

          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "新しいバージョンが利用可能です: $LATEST_VERSION (現在: $CURRENT_VERSION)"
            echo "has_update=true" >> $GITHUB_OUTPUT
            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          fi

  update-flutter:
    needs: check-has-flutter-update
    if: "${{ needs.check-has-flutter-update.outputs.has_update}}"
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      CURRENT_VERSION: ${{ needs.check-has-flutter-update.outputs.current_version }}
      LATEST_VERSION: ${{ needs.check-has-flutter-update.outputs.latest_version }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: develop

      - name: Install yq via snap
        run: sudo snap install yq

      # Replace version in .fvmrc
      - name: Replace version in .fvmrc
        run: |
          jq  \
            --arg latest_version "$LATEST_VERSION" \
            '.flutter = $latest_version' .fvmrc | sed '/^$/d' \
            > .fvmrc.tmp \
          && mv .fvmrc.tmp .fvmrc

      # Replace version in .vscode/settings.json
      - name: Replace version in .vscode/settings.json
        run: |
          jq  \
            --arg latest_version "$LATEST_VERSION" \
            '.dart.flutterSdkPath = ".fvm/versions/$latest_version"' .vscode/settings.json | sed '/^$/d' \
            > .vscode/settings.json.tmp \
          && mv .vscode/settings.json.tmp .vscode/settings.json

      # Install Flutter
      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # Replace Version in pubspec.yaml
      - name: Replace Version in pubspec.yaml
        run: |
          # Flutter version
          FLUTTER_STR="^$FLUTTER_VERSION" \
            yq eval --inplace '.melos.command.bootstrap.environment.flutter = strenv(FLUTTER_STR)' pubspec.yaml
          echo "Replaced Flutter version in pubspec.yaml: $FLUTTER_STR"

          # Dart version
          dart --version
          DART_VERSION=$(dart --version | awk '{print $4}')
          DART_STR="^$DART_VERSION" \
            yq eval --inplace '.melos.command.bootstrap.environment.sdk = strenv(DART_STR)' pubspec.yaml
          echo "Replaced Dart version in pubspec.yaml: $DART_STR"

      - name: Check pubspec.yaml
        run: |
          cat pubspec.yaml

      # Execute melos bootstrap
      - name: Execute melos bootstrap
        run: melos bootstrap

      # Create PR
      # https://github.com/peter-evans/create-pull-request
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        id: cpr
        with:
          delete-branch: true
          commit-message: "Update Flutter ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}"
          committer: "GitHub Actions <noreply@github.com>"
          base: ${{ github.head_ref }}
          branch: "update-flutter/${{ env.CURRENT_VERSION }}-${{ env.LATEST_VERSION }}"
          title: "Update Flutter ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}"
          body: |
            Update Flutter ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }} by GitHub Actions on ${{ github.ref }}
            by: ${{github.actor}}

            ## リンク
            - Flutter
              - [Flutter Release Notes](https://docs.flutter.dev/release/release-notes)
              - [Flutter Changelog](https://github.com/flutter/flutter/blob/master/CHANGELOG.md)
            - Dart
              - [What's new](https://dart.dev/resources/whats-new)
              - [Dart Changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md)
          labels: "Update Flutter"
          reviewers: ${{ github.actor }}
          draft: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
