name: Assign author

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  auto-author:
    name: Assign author to PR
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      # https://github.com/technote-space/assign-author
      - name: Assign author to PR
        uses: toshimaru/auto-author-assign@bdd7688cbf9e6d5683f02f8c7d8ae4062a254b6d # v3.0.2
