name: Check PR

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

jobs:
  pre-check:
    permissions:
      pull-requests: write
    outputs:
      src: ${{ steps.filter.outputs.src }}
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            src:
              - "**.dart"
              - "**.yaml"
              - "**/pubspec.lock"
              - "scripts/**"

      # https://github.com/peter-evans/create-or-update-comment
      - name: Comment
        if: ${{ steps.filter.outputs.src == 'false' }}
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > [!WARNING]
            > チェック対象ファイルの変更がなかったため、checkジョブをスキップしました

  regenerate-code:
    name: Regenerate code
    needs: pre-check
    if: ${{ needs.pre-check.outputs.src == 'true' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: re-generated code
        run: melos run rebuild --no-select

      - name: format
        run: melos format

      - name: fix
        run: dart fix --apply .

      - name: check difference
        run: |
          git add -N .
          git diff --name-only --exit-code

      # https://github.com/peter-evans/create-pull-request
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: failure()
        id: cpr
        with:
          delete-branch: true
          commit-message: "Auto format"
          committer: "GitHub Actions <noreply@github.com>"
          base: ${{ github.head_ref }}
          branch: "auto-format/${{ github.head_ref }}"
          title: "Auto format - ${{ github.head_ref }}"
          body: "Auto format by GitHub Actions on ${{ github.ref }}\nby: ${{github.actor}}"
          labels: "Auto Format"
          reviewers: ${{ github.actor }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

  test:
    name: Check format and Run test
    needs: pre-check
    if: ${{ needs.pre-check.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # https://github.com/invertase/github-action-dart-analyzer
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0
        with:
          fatal-infos: true

      - name: Report custom_lint result
        run: |
          echo "::add-matcher::.github/problem_matchers/custom_lint.json"
          melos run ci:report:custom_lint --no-select || result=$?
          echo "::remove-matcher owner=custom_lint::"

          if [ -n "$result" ]; then
            exit 1
          fi

      - name: Run test
        run: melos run report_test --no-select
        continue-on-error: true

      # https://github.com/dorny/test-reporter
      - name: Report test
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          name: "flutter test"
          path: "(app|catalog|packages/**)/test_report.log"
          reporter: "flutter-json"
          fail-on-error: "true"
