name: Check PR

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches-ignore:
      - "auto-format/*" # このActionで作成されたPRは対象外 (無限ループを防ぐため)

jobs:
  pre-check:
    permissions:
      pull-requests: write
    outputs:
      src: ${{ steps.filter.outputs.src }}
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      # https://github.com/dorny/paths-filter/tree/v3.0.2/
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            src:
              - "**.dart"
              - "**.yaml"
              - "**/pubspec.lock"
              - "scripts/**"

      # https://github.com/peter-evans/create-or-update-comment/tree/v4/
      - name: Comment
        if: ${{ steps.filter.outputs.src == 'false' }}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > [!WARNING]
            > チェック対象ファイルの変更がなかったため、checkジョブをスキップしました

  regenerate-code:
    name: Regenerate code
    needs: pre-check
    if: ${{ needs.pre-check.outputs.src == 'true' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      # https://github.com/actions/checkout/tree/v4/
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: re-generated code
        run: melos run regenerate_code --no-select

      - name: check difference
        run: |
          git add -N .
          git diff --name-only --exit-code

      # https://github.com/peter-evans/create-pull-request/tree/v6/
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@6cd32fd93684475c31847837f87bb135d40a2b79
        if: failure()
        id: cpr
        with:
          delete-branch: true
          commit-message: "Auto format"
          committer: "GitHub Actions <noreply@github.com>"
          base: ${{ github.head_ref }}
          branch: "auto-format/${{ github.head_ref }}"
          title: "Auto format - ${{ github.head_ref }}"
          body: "Auto format by GitHub Actions on ${{ github.ref }}\nby: ${{github.actor}}"
          labels: "Auto Format"
          reviewers: ${{ github.actor }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

  test:
    name: Check format and Run test
    needs: pre-check
    if: ${{ needs.pre-check.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout/tree/v4/
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # https://github.com/invertase/github-action-dart-analyzer/tree/v3/
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b
        with:
          fatal-infos: true

      - name: Report custom_lint result
        run: |
          echo "::add-matcher::.github/problem_matchers/custom_lint.json"
          melos run report_custom_lint:ci --no-select || result=$?
          echo "::remove-matcher owner=custom_lint::"

          if [ -n "$result" ]; then
            exit 1
          fi

      - name: Run test
        run: melos run report_test --no-select
        continue-on-error: true

      # https://github.com/dorny/test-reporter/tree/v1.9.1/
      - name: Report test
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
        with:
          name: "flutter test"
          path: "(app|catalog|packages/**)/test_report.log"
          reporter: "flutter-json"
          fail-on-error: "true"
