name: Production Release Tag PR
on:
  push:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
      - id: tagpr
        uses: Songmu/tagpr@163cd45f79765d46a829a18dd20df2df58ead690 # v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
