name: Production Release Tag PR
on:
  push:
    branches:
      - develop

permissions: {}

jobs:
  check:
    runs-on: ubuntu-slim
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - id: tagpr
        uses: Songmu/tagpr@d1b8138b7a31075141b6cd64103de9485ced7ac9 # v1.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
