name: Deploy App

on:
  push:
  workflow_dispatch:
    inputs:
      ios:
        description: "Build iOS app"
        required: false
        default: true
        type: boolean
      android:
        description: "Build Android app"
        required: false
        default: true
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  XCODE_VERSION: 26.1
  GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/179553945248/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-identity-provider
  GOOGLE_CLOUD_SERVICE_ACCOUNT: actions-eqmonitor-appdistro@eqmonitor-main.iam.gserviceaccount.com

jobs:
  define-matrix:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    outputs:
      deploy-ios: ${{ steps.define-environment-matrix.outputs.deploy-ios }}
      deploy-android: ${{ steps.define-environment-matrix.outputs.deploy-android }}
    steps:
      - name: Decide which app to deploy
        id: define-environment-matrix
        run: |
          platforms=()
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.ios }}" = "true" ]; then
              platforms+=("ios")
            fi
            if [ "${{ inputs.android }}" = "true" ]; then
              platforms+=("android")
            fi
          elif [ "${{ github.event_name }}" = "push" ]; then
              # [release only] タグがない場合は全プラットフォームをデプロイ
              echo "commit message does not contain [release only platform], deploy all platforms"
              platforms+=("ios" "android")
          else
            echo "Unknown event name: ${{ github.event_name }}"
            exit 1
          fi

          echo "デプロイするプラットフォーム: ${platforms[@]}"
          for platform in "${platforms[@]}"; do
            echo "deploy-${platform}=true" >> $GITHUB_OUTPUT
          done

  build-ios:
    needs: define-matrix
    if: ${{ needs.define-matrix.outputs.deploy-ios }}
    runs-on: macos-26
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-android
      cancel-in-progress: false
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v3.1.1
        with:
          install_args: "flutter xcbeautify"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      # https://github.com/maxim-lobanov/setup-xcode
      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Enable Swift Package Manager
        run: |
          flutter config --enable-swift-package-manager

      - name: Resolve dependencies
        working-directory: app
        run: flutter pub get --enforce-lockfile

      - name: Extract environment variables
        run: |
          cp environment/.env.dev environment/.env.prod

      - name: Configure iOS
        working-directory: app
        run: |
          flutter build ios --config-only \
            --no-codesign \
            --no-pub \
            --build-number=${{ github.run_number }} \
            --dart-define-from-file=../environment/.env.prod \
            --dart-define COMMIT_INFORMATION=${{ github.ref_name }}-${{ github.sha }}

      - name: Extract App Store Connect API Key
        working-directory: app/ios
        run: |
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 -d \
            > AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
          ls -l AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8

      - name: Archive
        working-directory: app
        run: |
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/ios/Runner.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
          | xcbeautify --renderer github-actions

      - name: Embed entitlements
        working-directory: app
        run: |
          codesign \
            --entitlements ios/Runner/Runner.entitlements \
            --force \
            --sign "-" build/ios/Runner.xcarchive/Products/Applications/Runner.app

          codesign --display --entitlements :- build/ios/Runner.xcarchive/Products/Applications/Runner.app/Runner  || true

      - name: Archive
        working-directory: app
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath . \
            -allowProvisioningUpdates \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_API_ISSUER_ID \
            -authenticationKeyID $APP_STORE_CONNECT_API_KEY_ID \
            -authenticationKeyPath "${{ github.workspace }}/app/ios/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8" \
          | xcbeautify --renderer github-actions

      # https://github.com/actions/upload-artifact
      - name: Upload ipa as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: EQMonitor-ios.ipa
          path: app/FlutterKaigi 2025.ipa
          if-no-files-found: error

  deploy-ios:
    needs: build-ios
    runs-on: macos-26
    environment:
      name: EQMonitor-iOS
    concurrency:
      group: ${{ github.workflow }}-ios
      cancel-in-progress: false
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      # https://github.com/actions/download-artifact
      - name: Download ipa
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: EQMonitor-ios.ipa
          path: build

      - name: List files
        run: ls -lah build/

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml .config/mise/mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v3.1.1
        with:
          install_args: "xcbeautify"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      - name: Upload Ipa to App Store Connect
        run: |
          xcrun altool \
            --upload-app \
            -f build/eqmonitor.ipa \
            --type ios \
            --apiIssuer ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }} \
            --apiKey ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}

  build-android:
    needs: define-matrix
    if: ${{ needs.define-matrix.outputs.deploy-android }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v3.1.1
        with:
          install_args: "flutter java uv python pipx:codemagic-cli-tools"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      - name: Accept Android License
        run: yes | flutter doctor --android-licenses

      - name: Extract keystore
        run: |
          echo "$SIGNING_KEY" | base64 -d > app/android/app/key.jks
          echo "$KEY_PROPERTIES" | base64 -d  > app/android/key.properties

      # https://github.com/google-github-actions/auth
      - name: Authenticate to Google Cloud Platform
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Fetch latest build number from Google Play Store
        id: fetch-latest-build-number
        run: |
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number \
            --credentials="@file:${{ steps.auth.outputs.credentials_file_path }}" \
            --package-name="net.yumnumm.eqmonitor" || echo "0")

          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
          echo "Build Number set to ${BUILD_NUMBER}."

      - name: Build Android (AAB)
        working-directory: app
        env:
          BUILD_NUMBER: ${{ steps.fetch-latest-build-number.outputs.BUILD_NUMBER }}
        run: |
          flutter build appbundle \
            --release \
            --build-number=${BUILD_NUMBER} \
            --dart-define-from-file=../environment/.env.prod

      - name: Upload aab as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: EQMonitor-android.aab
          path: app/build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error

  deploy-android:
    needs: build-android
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    environment:
      name: EQMonitor-Android
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v3.1.1
        with:
          install_args: "flutter java uv python pipx:codemagic-cli-tools"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      - name: Download artifact aab
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: EQMonitor-android.aab
          path: build

      - name: Output release version
        run: |
          VERSION=$(yq .version app/pubspec.yaml -r)
          echo "release_version=${VERSION}" >> $GITHUB_OUTPUT
          echo "[$VERSION]" > changelog.tmp

      - name: Output git log
        run: |
         # LAST TAG
          LAST_TAG=$(git describe --tags --abbrev=0)
          git log $LAST_TAG..HEAD --pretty=format:"- [%ad] %an: %s %h" >> changelog.tmp

          # 最大500文字
          head -c 500 changelog.tmp > changelog.txt
          if [ $(wc -c < changelog.txt) -gt 500 ]; then
            echo '...' >> changelog.txt
          fi

      - name: Generate JSON
        run: |
          jq -Rs '[{language: "ja-JP", text: .}]' changelog.txt > release-notes.json
          cat release-notes.json | jq

      # https://github.com/google-github-actions/auth
      - name: Authenticate to Google Cloud Platform
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Upload to Google Play
        run: |
          google-play bundles publish \
            --credentials="@file:${{ steps.auth.outputs.credentials_file_path }}" \
            --bundle app.aab \
            --track "internal" \
            --release-notes="@file:release-notes.json"
