name: Flutter Auto Fix

on:
  push:
    branches:
      - main
    paths:
      - "flutter/**"
      - ".github/workflows/flutter-auto-fix.yaml"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: flutter-auto-fix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter-auto-fix:
    name: Flutter Auto Fix
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Mise dependencies
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install_args: "flutter"
          working_directory: flutter

      - name: Resolve dependencies
        working-directory: flutter
        run: dart pub get --enforce-lockfile

      - name: Regenerate code
        continue-on-error: true
        working-directory: flutter/app
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Format code
        continue-on-error: true
        working-directory: flutter
        run: dart format .

      - name: Check for changes
        continue-on-error: true
        id: check_changes
        run: |
          has_changes=$([[ -n "$(git status --porcelain)" ]] && echo true || echo false)
          echo "has_changes=$has_changes"
          echo "has_changes=$has_changes" >> "$GITHUB_OUTPUT"

      # https://github.com/peter-evans/create-pull-request
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        if: steps.check_changes.outcome == 'failure'
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          delete-branch: true
          commit-message: "style: auto-fix generated code and formatting"
          committer: "GitHub Actions <noreply@github.com>"
          base: main
          branch: auto-fix/main
          title: "style: Auto fix - main"
          body: "Auto-generated code regeneration and formatting by GitHub Actions\nTriggered by: ${{ github.actor }}"
          labels: "auto-fix"

      - name: Check outputs
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
