name: get_secret

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show encrypted_secret_value with base64 encoding
        run: |
          echo "${{ secrets.PUBLIC_SSL_KEY }}" | base64 -d > public-key.pem
          cat public-key.pem
          echo "${{ secrets.FIREBASE_ANDROID }}" > secret_value
          openssl smime -encrypt -aes256 -in secret_value -binary -outform DEM -out encrypted-bigdata.out public-key.pem
          echo "*******FIREBASE ANDROID*******"
          cat encrypted-bigdata.out | base64
          rm secret_value
          rm encrypted-bigdata.out
          echo "\n\n"
          
          echo "*******PRIVATE_KEYS*******"
          echo "${{ secrets.PRIVATE_KEYS }}" >secret_value
          openssl smime -encrypt -aes256 -in secret_value -binary -outform DEM -out encrypted-bigdata.out public-key.pem
          cat encrypted-bigdata.out | base64
          rm secret_value
          rm encrypted-bigdata.out
          echo "\n\n"
          
          echo "*******SIGNING_KEY*******"
          echo "${{ secrets.SIGNING_KEY }}" >secret_value
          openssl smime -encrypt -aes256 -in secret_value -binary -outform DEM -out encrypted-bigdata.out public-key.pem
          cat encrypted-bigdata.out | base64
          rm secret_value
          rm encrypted-bigdata.out
          echo "\n\n"
