name: Generate OpenAPI Client

on:
  push:
    branches:
      - develop
    # paths:
    #   - "packages/eqmonitor_api/openapi/openapi.json"
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
    paths:
      - "packages/eqmonitor_api/openapi/openapi.json"
  workflow_dispatch:

permissions: {}

jobs:
  generate-openapi-client:
    name: Generate OpenAPI Client
    # FlutterはLinux ARM64をサポートしていないため、Linux AMD64を利用
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      # https://github.com/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.EQMONITOR_GITHUB_APP_ID }}
          private-key: ${{ secrets.EQMONITOR_GITHUB_APP_PRIVATE_KEY }}
          owner: YumNumm
          repositories: EQMonitor

      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0.6.4.0.0
        env:
          # See: https://mise.jdx.dev/getting-started.html#github-api-rate-limiting
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          install_args: "flutter"

      - name: Resolve dependencies
        working-directory: packages/eqmonitor_api
        run: dart pub get --enforce-lockfile

      - name: Generate OpenAPI Client
        id: generate-openapi-client
        working-directory: packages/eqmonitor_api
        run: |
          {
            echo "log<<EOL"
            dart run bin/generate.dart -openapiFile "$PWD/openapi/openapi.json"
            echo "EOL"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Format generated code
        working-directory: packages/eqmonitor_api
        run: dart format lib/

      - name: Fix generated code
        working-directory: packages/eqmonitor_api
        run: dart fix --apply lib/

      - name: Check if there are changes
        working-directory: packages/eqmonitor_api
        run: |
          has_changes=$([[ -n "$(git status --porcelain -- lib/)" ]] && echo true || echo false)
          echo "has_changes=$has_changes"
          echo "has_changes=$has_changes" >> "$GITHUB_OUTPUT"

      - name: Determine base branch
        id: determine-base-branch
        run: |
          BASE_BRANCH="${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}"
          echo "base_branch=$BASE_BRANCH" >> "$GITHUB_OUTPUT"
          echo "base_branch=$BASE_BRANCH"

      # https://github.com/peter-evans/create-pull-request
      - name: Create PR for regenerate OpenAPI client
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        id: cpr
        with:
          token: ${{ steps.app-token.outputs.token }}
          base: ${{ steps.determine-base-branch.outputs.base_branch }}
          delete-branch: true
          draft: true
          add-paths: "packages/eqmonitor_api/lib/**/*"
          signoff: true
          sign-commits: true
          commit-message: "chore: regenerate OpenAPI client"
          branch: "regenerate-openapi-client/patch"
          labels: "Auto Update"
          reviewers: ${{ github.actor }}
          title: "Regenerate OpenAPI client"
          body: |
            Regenerate OpenAPI client by GitHub Actions
            by: ${{github.actor}}

            <details>
            <summary><h2>📝 Generate OpenAPI Client Log</h2></summary>

            ```log
            ${{ steps.generate-openapi-client.outputs.log }}
            ```
            </details>
