name: Terraform Plan (Google Cloud)

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: terraform-gcp-prod-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/179553945248/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-identity-provider
  GOOGLE_CLOUD_SERVICE_ACCOUNT: actions-eqmonitor-writer@eqmonitor-main.iam.gserviceaccount.com

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/wc-changes.yaml

  validate:
    needs: changes
    if: needs.changes.outputs.terraform == 'true'
    permissions:
      contents: read
    uses: ./.github/workflows/wc-check-terraform-validate.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      target: googlecloud/environments/production

  plan:
    name: Terraform Plan (googlecloud/environments/production)
    needs:
      - changes
      - validate
    if: needs.changes.outputs.terraform == 'true'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        working-directory: terraform/googlecloud/environments/production
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Extract SOPS Age Key File
        working-directory: terraform
        run: echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml.example to mise.local.toml
        working-directory: terraform
        run: cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install_args: "opentofu aqua:suzuki-shunsuke/tfcmt"
          working_directory: terraform

      - name: Set environment variables
        working-directory: terraform
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo "$line" >> "$GITHUB_ENV"
            mask_value="${line#*=}"
            echo "::add-mask::${mask_value}"
          done

      # https://github.com/google-github-actions/auth
      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

      - name: Initialize
        run: tofu init

      - name: Plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tfcmt plan \
            -patch \
            -var "target:googlecloud/environments/production" \
          -- tofu plan -input=false

  status-check:
    name: Terraform Plan Status Check
    runs-on: ubuntu-slim
    timeout-minutes: 1
    needs:
      - validate
      - plan
    permissions: {}
    if: always()
    steps:
      - name: Check job results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
