name: Terraform Plan

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    outputs:
      targets: ${{ steps.define-matrix.outputs.targets }}
    steps:
      - name: Define matrix
        id: define-matrix
        run: |
          dirs="googlecloud/environments/production"

          # JSONの配列に変換し、outputsに設定
          targets=$(echo "$dirs" | jq -R . | jq -sc .)
          echo "targets=${targets}" >> $GITHUB_OUTPUT

  lint:
    name: Terraform Lint (${{ matrix.target }})
    needs:
      - define-matrix
    runs-on: ubuntu-slim
    timeout-minutes: 10
    strategy:
      matrix:
        target: ${{ fromJson(needs.define-matrix.outputs.targets) }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.1.1
        with:
          install_args: "terraform tflint aqua:suzuki-shunsuke/tfcmt"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      - name: Extract backend.tfbackend
        working-directory: terraform
        run: |
          echo "$TERRAFORM_BACKEND_CONFIGURATION" | base64 -d  \
            > backend.tfbackend

      - name: Check directory is not empty
        working-directory: terraform/${{ matrix.target }}
        run: |
          if [ -z "$(ls -A)" ]; then
            echo "Directory is empty! Please add a Terraform file to the directory."
            exit 1
          fi

      - name: Terraform init
        working-directory: terraform/${{ matrix.target }}
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform fmt
        working-directory: terraform/${{ matrix.target }}
        run: terraform fmt -check -diff

      - name: tflint
        working-directory: terraform/${{ matrix.target }}
        run: tflint

  plan:
    name: Terraform Plan (${{ matrix.target }})
    needs:
      - lint
      - define-matrix
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      issues: write
    strategy:
      matrix:
        target: ${{ fromJson(needs.define-matrix.outputs.targets) }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Extract SOPS Age Key File
        run: |
          echo "${{ secrets.AGE_KEY }}" > .config/age/age.txt

      - name: Copy mise.local.toml
        run: |
          cp mise.local.toml.example mise.local.toml

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.1.1
        with:
          install_args: "terraform tflint aqua:suzuki-shunsuke/tfcmt"

      - name: Set environment variables
        run: |
          for line in $(mise env --redacted --dotenv); do
            echo $line >> "$GITHUB_ENV"
            echo "::add-mask::${line#*=}"
          done

      - name: Change directory
        working-directory: terraform/${{ matrix.target }}
        run: |
          echo "Changed directory to terraform/${{ matrix.target }}"

      - name: Extract backend.tfbackend
        working-directory: terraform
        run: |
          echo "$TERRAFORM_BACKEND_CONFIGURATION" | base64 -d  \
            > backend.tfbackend

      - name: Check directory is not empty
        working-directory: terraform/${{ matrix.target }}
        run: |
          if [ -z "$(ls -A)" ]; then
            echo "Directory is empty! Please add a Terraform file to the directory."
            exit 1
          fi

      - name: Terraform init
        working-directory: terraform/${{ matrix.target }}
        id: init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform fmt
        working-directory: terraform/${{ matrix.target }}
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform validate
        working-directory: terraform/${{ matrix.target }}
        id: validate
        run: terraform validate

      # https://github.com/google-github-actions/auth
      - name: Authenticate to Google Cloud Platform
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: "projects/179553945248/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-identity-provider"
          service_account: "actions-eqmonitor-writer@eqmonitor-main.iam.gserviceaccount.com"

      - name: Terraform plan
        working-directory: terraform/${{ matrix.target }}
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tfcmt plan \
            -patch \
            -var "target:${{ matrix.target }}" \
          -- terraform plan -input=false
