name: Release Please

on:
  push:
    branches:
      - develop

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
