name: Terraform Validate

on:
  workflow_call:
    inputs:
      target:
        description: "Target directory relative to terraform/"
        required: false
        type: string
        default: "googlecloud/environments/development"

permissions:
  contents: read

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install_args: "opentofu"
          working_directory: terraform

      - name: Check format
        working-directory: terraform
        run: tofu fmt -check -diff -recursive

      - name: Initialize
        working-directory: terraform/${{ inputs.target }}
        run: tofu init -backend=false

      - name: Validate
        working-directory: terraform/${{ inputs.target }}
        run: tofu validate
