name: Detect changes

on:
  workflow_call:
    outputs:
      flutter:
        value: ${{ jobs.changes.outputs.flutter }}
      eqmonitor_map_scene_spike:
        value: ${{ jobs.changes.outputs.eqmonitor_map_scene_spike }}
      typescript:
        value: ${{ jobs.changes.outputs.typescript }}
      terraform:
        value: ${{ jobs.changes.outputs.terraform }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    permissions:
      contents: read
      pull-requests: read
    outputs:
      flutter: ${{ steps.filter.outputs.flutter }}
      eqmonitor_map_scene_spike: ${{ steps.filter.outputs.eqmonitor_map_scene_spike }}
      typescript: ${{ steps.filter.outputs.typescript }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          base: ${{ github.event.merge_group.base_sha || '' }}
          filters: |
            flutter:
              - 'app/**'
              - 'packages/**'
              - 'tools/**'
              - 'pubspec.yaml'
              - 'pubspec.lock'
              - 'mise.lock'
              - 'analysis_options.yaml'
              - '.github/workflows/flutter.yaml'
              - '.github/workflows/wc-check-dart-*.yaml'
              - '.github/workflows/pr-flutter-check.yaml'
              - '.github/workflows/wc-changes.yaml'
            eqmonitor_map_scene_spike:
              - 'packages/eqmonitor_map/**'
              - 'tool/eqmonitor_map/**'
              - '.gitignore'
              - 'mise.toml'
              - 'mise.lock'
              - '.github/workflows/wc-check-eqmonitor-map-scene-spike.yaml'
              - '.github/workflows/pr-flutter-check.yaml'
              - '.github/workflows/wc-changes.yaml'
            terraform:
              - 'terraform/**'
              - '.github/workflows/terraform.yaml'
              - '.github/workflows/wc-check-terraform-*.yaml'
