name: Terraform Validate

on:
  workflow_call:
    inputs:
      target:
        description: "Target directory relative to terraform/"
        required: false
        type: string
        default: "googlecloud/environments/development"

permissions:
  contents: read

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        with:
          install_args: "opentofu"
          working_directory: terraform

      - name: Check format
        working-directory: terraform
        run: tofu fmt -check -diff -recursive

      - name: Initialize
        working-directory: terraform/${{ inputs.target }}
        run: tofu init -backend=false

      - name: Validate
        working-directory: terraform/${{ inputs.target }}
        run: tofu validate
