name: kyoshin_observation_point_converter_internal
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  geojson_vi: ^2.2.4
  http: ^1.2.1
  kyoshin_observation_point_types:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/kyoshin_observation_point_types
  maps_toolkit: ^3.0.0

dev_dependencies:
  eqmonitor_lints:
    path: ../eqmonitor_lints
  altive_lints: ^1.16.0
